### ISSUE TITLE
Language doc is missing components and not generated from comments

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/stacks-blockchain#1005]
Currently, we only output special functions in the JSON. We should include the entire language in the output. As it stands `src/vm/docs/mod.rs` doesn't contain other supported elements. I'm having to dig for those.

Not clear what's possible, but there is an advantage in pulling comments from the _code where these things are implemented_ rather than building a file to generate strings -- which it appears we did.  Looks like the `src/vm/docs/mod.rs`  is manually maintained file whose sole purpose is to generate documentation --- which I could have just written in a Markdown file.

The actual definitions of the functions `src/vm/functions` is here correct? Effectively, if you co-locate the documentation via comments _in the code where the functions/types/variables_ are defined and then extract those comments into JSON --- I can do way more as a writer. Right now, I'm digging around in the code and comparing it to `src/vm/docs/mod.rs` which is inefficient for me and results in questions to the team which slows development.

If we don't want to actually generate from comments, we are better off not keep `/src/vm/docs/mod.rs` --- extra work all around. I'll just write the docs direct from the code files I'm finding and not bother generating.  

Happy to explain this further...if it isn't clear. Please let me know if you did this setup for some other reason or just because I said "generate a json file" --- right now I'm in guilt mode. 😞

**Comment by kantai** [comment]
There's a couple reasons we have the setup we currently do:

1. The state of documentation generation via source code is pretty feature-sparse right now in Rust. It didn't seem like it would be possible to do the kind of generation we wanted to do via Rust comment generation, since there's not actually a 1-1 mapping between functions defined in Rust and our language runtime (that is, there are Rust functions which _implement_ our native functions, but they do not have the same API -- Rust doesn't even understand our language's types).

2. The way `docs/mod.rs` is built right now at least provides a forcing function on us whenever new functions are added to the language -- if a new function is added to the language, documentation must be added or the project will not compile at all. This is a little bit better of a situation where we just had separate documentation entirely.

**Comment by moxiegirl** [comment]
@kantai Thanks for the explanation. I kind of thought that it might be a Rust thing but wasn't sure.  Did y'all take a look at https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html?

 I agree `2` having a check is better than nothing.

**Comment by kantai** [comment]
Yep -- using rustdoc was the original plan, but it seemed like it wasn't going to work well for us given issue 1 above (that the functions defined in rust are not themselves the clarity functions).

**Comment by moxiegirl** [comment]
OK, I'm going to leave this open but assign it to me. At the least, I can document what we are doing and the key files to look for other things.
