### ISSUE TITLE
QUESTION: Stacks Smart Contracts Upgradable?

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#1037]
I'm curious if Stacks smart contracts will be upgradable?  If so, will we be able to use some basic 'library' contracts without having them change from underneath us? I.e. will we be able to pin to a specific version of a contract?

**Comment by friedger** [comment]
Smart contract are blockstack addresses build on the hash of the code. If the code changes to you have new hash -> new address -> new contract.

**Comment by kantai** [comment]
@dantrevino --

Good question -- for now, we don't have any mechanism for making a contract upgradable -- it's a hard feature to support, since smart contracts are ultimately relied upon to be immutable.

**Comment by lgalabru** [comment]
@dantrevino  Upgradability is hard, but what's your take on traceability?

As is, as a user interacting with a contract, I'd like to be able to look at the history of that contract from my wallet interface, and if for some reason, I'm not interacting with the latest version, or if one of the contract being called is not pointing to the latest and greatest version, I'd like to get a huge warning.

**Comment by jcnelson** [comment]
I think the goal here is to go with traceability instead of upgradability.  The difference is that with traceability, all prior versions of the contract continue to exist and be used.  As long as you publish contracts under the same key(s), anyone will be able to see the history of revisions you've made, as well as find the "latest" version.  The revision would be encoded in the smart contract name (e.g `_v2`, `v2_1`, etc.).

We're still working on what the revision scheme would look like, but such schemes are beyond the scope of Clarity.
