### ISSUE TITLE
Flat-file MARF

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1130]
To reduce seeks and remove other crash-consistency problems, restructure the on-disk MARF representation to be a single file (or a fixed set of files in the same directory).

**Comment by jcnelson** [comment]
To implement this, we could create a Trie database which contained a table with rows consisting of (index block hash, parent index block hash, trie blob) triples.  This mostly lines up with how we access Trie data on disk right now (i.e. through a seekable file-like handle), and it gains us the speed and safety of putting everything into a single file.

**Comment by kantai** [comment]
Benchmarks for an implementation via sqlite with 1 row per block, primary key = local block id, index on index block hash. The block data is stored in a blob, and accessed (but not written) via the sqlite incremental blob interface (meaning that sqlite isn't reading in the whole blob on lookup, but rather just seeking to the node being read):

A benchmark which creates 20 blocks, each with 5k writes and performing 20k reads on each block:

```
                      total    user    sys time
Current:                 26      17      9
sqlite :memory:          28      27      1
sqlite fs:              139      57     81
sqlite fs w/
cache_size=2GB:          44      33     11
sqlite fs w/
mmap_size=2GB:           43      32     11
```

Compared are the current fs backed implementation, a sqlite connection to `:memory:`, a plain sqlite connection to fs, and then connections using mmap and cache_size pragmas.

Now, I also ran a benchmark that first constructed a 40 block marf on disk, then measured 20k reads from the on-disk marf:

```
Current:                1.6s
sqlite:                17.8s
sqlite w/
cache_size=2GB:         5.3s
```

Looking at these numbers does not paint the best picture for performance when it comes to switching to a sqlite backed store versus the filesystem backed approach. Granted, these numbers may begin to approach each other as the size of the MARF grows (and the disk cache becomes less effective than it is currently), but I am not convinced of that. There's also a little room for improvement in the sqlite implementation over the FS implementation in the resolution of back-pointers. Currently, the sqlite implementation mimics the FS implemenation when walking a back pointer -- it takes the local u32 "block id" and looks up the corresponding block hash, "opens" that block hash (by looking up the associated block id in the database -- since that block id is just the sqlite row id in this implementation), and the to read from the pointer, it does the blob open using the row_id. The sqlite implementation could skip two of those steps -- it can service backpointers directly using the row_id and the pointer. However, I'm not sure how much improvement that would actually provide.

I think there's a couple of options here:

1. Accept the degraded MARF performance as the price of business in sqlite.
2. Test the sqlite implementation with the simplified backpointer resolution (and hopefully it's way faster?)
3. Attempt to resolve #1402 with a hybrid strategy -- use a sqlite table to manage the local only block identifiers as opposed to the current system which manages that block map in memory (and requires scanning the directory for updates). This would also require implementing a read-only mode for a TrieFileStorage struct which ignores the temporary / lock files.

**Comment by kantai** [comment]
Update: added somewhat simplified backpointer resolution, which does improve speed a bit. But more importantly, I am trying to benchmark with larger MARFs, and the read performance does seem to collapse between the two implementations:

At 400 blocks (which is about 1.3 GB on disk):

20k reads takes ~8s with the fs-backed approach, and ~11s with a caching sqlite.

Am working on building up a 1k block sample to test as well, but it does seem like at the smaller MARF sizes, the OS filesystem cache may be providing the fs-backed implementation with an advantage that would disappear at larger chainstate sizes.

**Comment by jcnelson** [comment]
> Am working on building up a 1k block sample to test as well, but it does seem like at the smaller MARF sizes, the OS filesystem cache may be providing the fs-backed implementation with an advantage that would disappear at larger chainstate sizes.

This is to be expected.  In the larger MARF tests, such as the one that writes 1 million key/value pairs, the filesystem performance noticeably slows down due to exceeding the disk cache size.  Is there a way you can disable the disk cache when testing the filesystem implementation, to make the comparison more fair?

The Stacks blockchain will spend the vast, vast majority of its lifespan with a MARF that is too big to fit into the disk cache, so it makes perfect sense to me to optimize the MARF for fast access from cold cache.  Also, the key improvements from a sqlite-based storage system are crash consistency [1] and concurrent read/write access (i.e. without us having to implement it).  While I was hoping that sqlite-backed storage would also be faster than the filesystem implementation, I nevertheless consider these improvements to be so important that I'd even be willing to sacrifice some performance to get them (so, I'm in favor of option (1) and/or (2)).

If we did want to do a hybrid approach (3) by keeping data in the filesystem but metadata in a sqlite database, then one requirement I think we'll want to have is to (a) make the sqlite metadata database commit to the hash of each `TrieRAM` file, and (b) make it so a Stacks node verifies the integrity of its Trie files each time it boots up (so we can at least detect when corruption happens).

> At 400 blocks (which is about 1.3 GB on disk):

Damn, that's pretty big.  How many key/value pairs are you inserting per block?

[1] Our filesystem implementation is _not_ crash-consistent -- `fsync(2)`-ing the `TrieRAM` file is not enough.  There are surprisingly many ways that a particular filesystem implementation _actively works against_ providing crash-consistency in the name of performance.  For anyone else reading this, there's a nice overview on just how badly things can go wrong with files [here](https://danluu.com/deconstruct-files/) (as well as links to research papers on the subjects).

**Comment by zone117x** [comment]
Quick note -- this issue and the few blocked issues are critical for getting a meaningful sidecar and Explorer shipped

**Comment by kantai** [comment]
> Damn, that's pretty big. How many key/value pairs are you inserting per block?

5,000 -- and they are all inserts, rather than updates, which means there will be a lot of promotion in the trie nodes.

> The Stacks blockchain will spend the vast, vast majority of its lifespan with a MARF that is too big to fit into the disk cache, so it makes perfect sense to me to optimize the MARF for fast access from cold cache.

Yep -- I agree -- currently building up a ~8GB over 1000 blocks MARF to test read performance on. I'll poke around with disabling my disk cache as well.

>  Also, the key improvements from a sqlite-based storage system are crash consistency [1] and concurrent read/write access (i.e. without us having to implement it). While I was hoping that sqlite-backed storage would also be faster than the filesystem implementation, I nevertheless consider these improvements to be so important that I'd even be willing to sacrifice some performance to get them (so, I'm in favor of option (1) and/or (2)).

Sounds good to me, though I want to make sure that they perform pretty similarly on cold-cache workloads.

**Comment by jcnelson** [comment]
> 5,000 -- and they are all inserts, rather than updates, which means there will be a lot of promotion in the trie nodes.

Hmm, I wonder if there should be a separate issue to store a compressed `TrieNode` representation, since nodes can have a lot of free child slots.

**Comment by kantai** [comment]
From what I've witnessed poking around with a read benchmark on the large MARF (after purging my OS disk cache), the SQLite implementation will be around 2x slower than the filesystem one on SSDs. On a spinning disk, this will probably not be the case. Setting the sqlite page size to a large value also improved performance, but I think we should worry about tuning the performance later on, and instead go with the straight-forward SQlite implementation (rather than a hybrid approach) for the immediate benefits of crash consistency and concurrency support.
