### ISSUE TITLE
Proposal: inequalities on (buff 1) 

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1172]
In the context of BNS, we need to run some processing on buffers (detect vowels, digits, etc).
I'm ending up writing:
```
 (or 
    (eq? char "0") 
    (eq? char "1") 
    (eq? char "2") 
    (eq? char "3") 
    (eq? char "4") 
    (eq? char "5") 
    (eq? char "6") 
    (eq? char "7") 
    (eq? char "8") 
    (eq? char "9"))
```

when something like this would be more concise:
```
(and (>= char 0x30) (<= char 0x39))
```

**Comment by njordhov** [comment]
**I suggest keeping the level of abstraction above character codes, and avoid introducing a character type.**

One option is to have a built-in function to test whether a string is numerical, like:

```clojure
(is-numeric char)
```

An alternative is to provide a function to test whether a string contains a substring:

```clojure
(is-substring char "0123456789" )
```

If the goal is to match patterns in string buffers, `regular expressions` could provide a generalized approach, rather than introducing more specialized functions and test logic.

**Comment by lgalabru** [comment]
https://github.com/blockstack/stacks-blockchain/issues/1624 is probably a better path. closing now.
