### ISSUE TITLE
Apply maximum memory limit for contract execution

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1306]
Similar to tracking the runtime cost of operations, and setting a limit for usage, the Clarity VM must apply a limit for memory consumption during contract execution. In particular, it will need to track the memory consumed by:

1. Contract constants
2. Bound function arguments
3. Bound let and match arguments
4. Contract code

Importantly, this tracker will need to operate globally (much like the current cost tracker, and the call stack) to handle function calls, etc.

**Comment by njordhov** [comment]
The restrictions on *variable shadowing* and *function re-entry* can be leveraged to determine a boundary for memory consumption before runtime and to avoid having to enforce the boundary at runtime by possibly minimize or even eliminate the need for a call stack.

The contract constants and function argument/variable variable bindings can be kept in global table(s), avoiding using the stack thanks to shadowing (see #1325). The function call stack is limited by the number of defined functions, due to the restriction on re-entry; The call stack can optionally be eliminated by each function having a pre-allocated slot to hold return context.

**Comment by diwakergupta** [comment]
This was addressed in #1329
