### ISSUE TITLE
Implement miner chainstate rollbacks in presence of errors

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1376]
As encountered in https://github.com/blockstack/stacks-blockchain/issues/1374

**Comment by kantai** [comment]
I believe I know what the source of these errors is --

The _miner_ code `chainstate::stacks::miner` uses `process_tx` when it tries to process a transaction -- that's fine. The problem is that if the miner tries to process a transaction that turns out to _invalidate_ the block, then it needs to:

1. Not process any of the mutations for the execution of that transaction. This appears to be handled correctly.
2. Not process the _fee_ for the transaction -- this does not appear to be handled correctly, and is the cause of the block header hashes not matching -- the chainstate of the miner processed the fees for a transaction not included in the block.

Fixing this will be a little involved -- the "fee processing" step of the transaction processing needs to be wrapped in the same `begin, commit` wrapper as the transaction payload's.

**Comment by jcnelson** [comment]
Posting a (not on Github) conversation @lgalabru and I had about this a few days ago:

```
ludo  1:09 AM
I've been replaying friedger scenario with both #1379 and #1378 merged, and I'm still getting a halt, but I think I've found the issue.
When the VM is throwing an error, the VM is rolling back, however the fees are not:

        let fee = StacksChainState::pay_transaction_fee(clarity_tx, tx, &payer_account)?;
        let tx_receipt = StacksChainState::process_transaction_payload(clarity_tx, tx, &origin_account)?;

That would be fine if the transaction was included in the block, but it's not the case:

            StacksChainState::process_transaction(clarity_tx, tx)?;
            // save
            self.txs.push(tx.clone());

We're unwrapping before the push, meaning the tx is not part of the block, but paying the fee did update the block hash in a way that can't be reproduced by nodes trying to append this block to their chain (edited) 

jude  1:24 AM
Ah, you're saying that in StacksBlockBuilder::try_mine_tx, we need to roll back the VM to the point right before the erroneous transaction began?
the miner's behavior is definitely buggy here -- unlike StacksChainState::append_block(), the miner won't revert the Clarity VM transaction if it finds a bad transaction

ludo  1:28 AM
yeah either that, or debiting the fee after the StacksChainState::process_transaction_payload which is what will probably happen anyway, since we need to execute the code for getting the dynamic cost (edited)

jude  1:30 AM
IIRC, if a TokenTransfer can't pay the amount given, then the entire block should be invalid. Same goes for transactions with invalid nonces
i.e. including these kinds of invalid transactions is evidence that the miner screwed up, and therefore the miner's block should not be accepted
if we unconditionally do self.txs.push(tx.clone()), does the problem go away?

ludo  1:33 AM
yes I think so

jude  1:33 AM
cool!
```

**Comment by kantai** [comment]
> Relevant part is here: if we unconditionally do self.txs.push(tx.clone()), does the problem go away?. I think the state root mismatch error in particular is coming from the fact that the miner won't include the buggy transaction in the block, so when the peer processes the block, it rejects it as invalid. Can you confirm this @kantai?

Yeah -- I saw that conversation.

That gets rid of the state root mismatch error, but it doesn't solve the problem -- either way the block constructed _should be invalid_, whether the validator figures that out with a state root mismatch or via a transaction error. Instead, a miner needs a way to recover the block.

> More generally, if the miner code is going to try to mine a transaction that could fail, then the miner needs to process the transaction within a single Clarity begin/commit context, and roll back that context if the transaction fails. I think this could be achieved by making it so StacksChainState::process_transaction() takes a ClarityTx to use throughout the entirety of processing the given Stacks transaction.

To a certain extent, that's already the case. The same ClarityTx instance is used everywhere in the same block. However, a ClarityTx is scoped at a "block level", rather than at a transaction level. Once a state change has been processed by the ClarityTx via run_contract_call, initialize_smart_contract, or with_clarity_db, that state is written to the MARF, and the only way to undo that change would be via rolling back the block. Of course, the Clarity DB supports finer grained rollbacks (that's how it handles the abort callbacks for post-conditions), so we could support this, but a few different places would need to be updated.

**Comment by kantai** [comment]
I'll work on patching this behavior.
