### ISSUE TITLE
Testnet: network code is slow to respond

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1416]
The testnet node doesn't appear to be calling `PeerNetwork::run()` often enough.  Per @kantai's explanation, this may be because the testnet node is constantly opening up a `chainstate`, `burndb`, and `mempool` each time it calls `PeerNetwork::run()`, and this can take a few seconds.

**Comment by hstove** [comment]
Is this similar to the RPC API endpoints typically being a bit slow (5-10s)? Or is that more related to #1402 ?

**Comment by jcnelson** [comment]
They are related issues.  If the slowness is indeed caused by repeatedly opening the chainstate, burndb, and mempool each time the node tries to do socket I/O, then fixing #1402 will enable this issue to be solved (i.e. the node can instead maintain a persistent read-only handle to all of these databases)

**Comment by kantai** [comment]
I think there's probably two things going on. One is #1402 is slowing some things down (in addition to just causing tons of PartialWrite failures, and otherwise abusing the implementation in ways it shouldn't be).

The other (and probably more immediate) is the poll_timeout parameter in the PeerNetwork::run function -- the helium node in master hardcodes that to `5000`, but that has negative consequences because the PeerNetwork run function handles two sockets -- it polls one and then the other. This means that if p2p socket doesn't have any incoming requests, it will stall the handler thread for 5s before polling the other socket. You can see that setting the poll_timeout to something like `50` leads to much more responsive RPC calls. However, that makes the poller thread essentially busy loop for data, which is not a good strategy. The thread should be polling both sockets at the same time.

**Comment by jcnelson** [comment]
Yup, that's probably the bigger contributor to time usage.  We need to poll both sockets simultaneously.

**Comment by jcnelson** [comment]
I'll split out the polling issue into a separate issue: https://github.com/blockstack/stacks-blockchain/issues/1423
