### ISSUE TITLE
Push mempool tx updates to event observer

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1547]
Showing transactions (near) immediately after submission is a primary use case for the sidecar / explorer. 
It can be implemented using the existing http event observer (e.g. POST mempool txs to a new path).

**Comment by aulneau** [comment]
This would _greatly_ improve the UX of the explorer. If possible I'd love for this to be of high priority.

**Comment by diwakergupta** [comment]
Sounds like a useful nice-to-have. We'll try to get to it in the next sprint.

**Comment by aulneau** [comment]
I'm curious the status of this ticket -- I would and have tried to suggest that this is more than a nice-to-have feature. I think this would drastically improve the experience of folks when they are interacting with the network.

**Comment by hstove** [comment]
Just want to :+1: this, as I'm working on the demo app, something like this would be a really nice UX improvement!

Right now, the app will broadcast a TX and show a link to the explorer. The explorer is just a 404 page. You have no way of knowing if the TX was even broadcasted.

With this, the explorer page would immediately have rich details about the transaction you just made, instead of having to wait for a confirmation just to peek inside of your transaction.

**Comment by diwakergupta** [comment]
> I'm curious the status of this ticket -- I would and have tried to suggest that this is more than a nice-to-have feature. I think this would drastically improve the experience of folks when they are interacting with the network.

Yes and that feedback is well received. As you can see this issue is/was planned for the current sprint (ending next Tuesday).

However keep in mind that right now we're have 2 workstreams on the blockchain-team: one is working on PoX tasks (since there's a LOT of work yet to be done there); and the other is focused on immediate testnet blockers / improvements, so we just haven't had the bandwidth to prioritize this.

I'm happy to get feedback on specific tasks the blockchain team is doing right now that we should drop in favor of this. Otherwise, we'll try to get to this as soon as we can.

**Comment by aulneau** [comment]
Cool, thanks for the update!

> I'm happy to get feedback on specific tasks the blockchain team is doing right now that we should drop in favor of this. Otherwise, we'll try to get to this as soon as we can.

I'm not sure that is a totally fair request -- I don't have context for the other work going on nor am I in any kind of position to make suggestions for what should/could get dropped (I don't want to be in that position). I took a look at the other issues in this sprint but I have no idea what meaning or importance they have. I also don't have any ability to judge the amount of work this feature would take to do. 

It's coming towards the end of the sprint and I was mostly hoping to check in to see what the status of this was (unassigned, etc), and to reiterate how this would improve the overall experience of everyone interacting with our network. 100% understand there is a lot going on and not trying to barge in and request folks to change their focus, more-so looking to see how to make a case for the importance of a given feature.

I'd also like to ask what the best way would be to talk about these kinds of issues where the potential importance / gain might not be agreed upon by the various folks involved?

**Comment by diwakergupta** [comment]
> > I'm happy to get feedback on specific tasks the blockchain team is doing right now that we should drop in favor of this. Otherwise, we'll try to get to this as soon as we can.
> 
> I'm not sure that is a totally fair request -- I don't have context for the other work going on nor am I in any kind of position to make suggestions for what should/could get dropped (I don't want to be in that position). I took a look at the other issues in this sprint but I have no idea what meaning or importance they have. I also don't have any ability to judge the amount of work this feature would take to do.

You're right, that wasn't fair. My bad.

> I'd also like to ask what the best way would be to talk about these kinds of issues where the potential importance / gain might not be agreed upon by the various folks involved?

As of last week, the entire DevX team had been invited to the Blockchain team weekly meetings. Subsequently we had a meeting on 5/20 to specifically align on dependencies around sidecar and explorer. As a follow up from that meeting, I believe @agraebe has scheduled a weekly blockchain/devx sync going forward. I hope that gives us plenty of touch points to surface dependencies and discuss prioritization?

**Comment by agraebe** [comment]
fyi - the first devx / blockchain sync is next Tuesday. Topics like this are great for the sync meeting

**Comment by diwakergupta** [comment]
Fixed with #1654
