### ISSUE TITLE
Inconsistent Nonce required

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1572]
**Describe the bug**
After nonce 2 was expected later nonce 1 is expected.

WARN [158923**6140.864**] [src/chainstate/stacks/miner.rs:595] Failed to apply tx 6f67cdce9dc73242b71952877f3cbe290b62276040e05c5aa9b29c41859244ca: InvalidStacksTransaction("Bad nonce: origin account ST1CV2J4FK96CQM2TNMABV5YBF620R175GCVHM192 nonce of tx 6f67cdce9dc73242b71952877f3cbe290b62276040e05c5aa9b29c41859244ca is 0 (expected 2)")

WARN [158923**6261.344**] [src/chainstate/stacks/miner.rs:595] Failed to apply tx 6f67cdce9dc73242b71952877f3cbe290b62276040e05c5aa9b29c41859244ca: InvalidStacksTransaction("Bad nonce: origin account ST1CV2J4FK96CQM2TNMABV5YBF620R175GCVHM192 nonce of tx 6f67cdce9dc73242b71952877f3cbe290b62276040e05c5aa9b29c41859244ca is 0 (expected 1)")

**Steps To Reproduce**
1. launch neon miner
2. deploy contract with other address than miner
3. call contract with miner address

**Expected behavior**
expected nonces should increase over time

**Comment by jcnelson** [comment]
This is happening because the miner is checking all outstanding transactions in the mempool, and reporting that some of them cannot be used to build the next block.  The logic that performs this check is the same logic that validates blocks, so it emits warnings when an unusable transaction is found.  The mempool itself does not delete transactions once they're mined, since a transaction can get re-mined in a different fork.

The `is 0 (expected 2)` part indicates that the given transaction's nonce is 0, but the account's nonce is 2.  The fact that it is increasing means that the account's transactions have been successfully mined.

**Comment by diwakergupta** [comment]
@friedger doesn't sound like this is a bug. If so, can you close? Thanks.

**Comment by friedger** [comment]
I don't understand why it is expecting 2 and thereafter 1
