### ISSUE TITLE
Neon miner must include a change output in VRF registrations

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1614]
Unfortunately, while #1588 fixed the dust output problem, it created a separate issue for VRF key registrations -- currently, VRF key transactions _need_ to have an output to validate corresponding block commits.

To support this, the neon miner needs to supply a second output in all cases. To support this, the bitcoin regtest controller should filter out any UTXOs that are smaller than 5500 + tx_fee, so that the change address is always generated.

**Comment by jcnelson** [comment]
To be clear, the second output is not intended to be a change output; it's meant to provide a way to link the VRF key register transaction to the block-commit transaction in order to prove that the same principal mining the block is the principal who registered the VRF public key.  Open to other ways to encode this linkage.

**Comment by diwakergupta** [comment]
For anyone interested / impacted by this issue, it manifests as a `Failed to parse leader key register tx` warning in the logs, like so:

```
WARN [1590072650.743] [src/burnchains/burnchain.rs:436] Failed to parse leader key register tx 20dd7756e98544b48e58c8f6e51a6aebf1c753f21bc79532adfe9cf3eff5ef9e data 42f198477825044a93123f2a0f431c903a3f44084579512084b36916cfa111745e1ca8c9cc7eb15023a5ca00b4dd4df50d2a06e3: InvalidInput
```
