### ISSUE TITLE
Support storing traits in variables

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1659]
**Is your feature request related to a problem? Please describe.**
Moloch dao (https://github.com/MolochVentures/moloch) allows to add new tokens to the list of accepted payments via proposals

**Describe the solution you'd like**
Allow something like
```
(contract-call? (get-var current-trait) do-something )
```
**Describe alternatives you've considered**
Include the trait in all public function calls

**Additional context**
Probably reentrance is the biggest problem with this feature request. Is that true?

**Comment by jcnelson** [comment]
This would likely break major static analysis guarantees Clarity offers.  In particular:

* This would make it intractable to determine the maximum cost of each code path, since you can now have data-dependent branches to any materialized contract address.  This in turn makes transaction fee estimation and mining much harder.

* This would make it intractable to determine the code reachable from a given `contract-call`, which invalidates a major safety feature of Clarity -- the ability to know in advance which functions could be called.

* This would make it intractable to verify the absence of reentrancy and recursion at instantiation time.  While these could both still be caught at runtime, the absence of a static check for them makes it much easier to deploy buggy contracts.

However, I don't think the absence of storing traits in variables makes it impossible to build a DAO like this.  Instead, the DAO code would need to be structured as a set of contracts that the user can pass as trait implementations via `contract-call` transactions.  The user's client would need a way to discover and select the right contract to use for payments, but this isn't to hard (you could store pointers in the DAO contract itself, for example).

**Comment by psq** [comment]
As much I'd like to have this ability, I agree with @jcnelson that allowing a contract to call an other contract based on a trait it stores would break one of the core design principle of Clarity where you can statically calculate the cost of calling that contract.

As I suggested in discord just a bit ago (https://discordapp.com/channels/621759717756370964/713087894260023377/718244036770791486), deploying a new contract each time may make sense, and I think I can make it work in the case of `swapr`.  There are some downsides, but manageable: increased cost as deploying a contract vs invoking can be orders of magnitudes more expensive, and increased complexity.

@friedger happy to discuss with you further how this could work in your case.

**Comment by psq** [comment]
Still would use traits, more as a way to show intent to other contract developers, as the static analyzer is still capable of determining whether the contract you call from an other has the require methods with the proper signatures.

**Comment by njordhov** [comment]
> `(contract-call? (get-var current-trait) do-something)`

@friedger What exactly is the `current-trait` variable supposed to contain? Also, how would you concretely implement the functionality with the current limitations?

**Comment by psq** [comment]
@njordhov that's part of the solution, but I don't think this is sufficient.  For more on this, see my alternative proposal, which would help without having to store traits: https://github.com/blockstack/stacks-blockchain/issues/1663

**Comment by kantai** [comment]
Closing this -- for the reasons @jcnelson mentioned, we will not support this feature in Clarity (implementation of this feature is essentially arbitrary dynamic dispatch).

#1663, however, is viable, and should allow most use cases.
