### ISSUE TITLE
Chain View Refactor: StacksChainState / Stacks Block DB Identification

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1677]
Modify the Stacks chain state and Stacks block DB to identify blocks as belonging to their (burnchain block, PoX fork ID) pair (i.e. replace BurnchainHeaderHash with SortitionID)

**Comment by jcnelson** [comment]
Working through this, it's clear that we need a stable, deterministic identifier that not only identifies which burnchain block a Stacks block belongs to, but also identifies which PoX fork it belongs to.  Because the history of valid burnchain operations can fork due to the (un)availability of anchor blocks in PoX reward cycles, I'm going to modify the `ConsensusHash` definition to represent PoX forks as well as burnchain operations.

The `ConsensusHash` will be derived from only the sequence of burnchain operations processed in a PoX fork, instead of all burnchain operations.  It will continue to be the tail of an authenticated skip-list tower (i.e. the hash of a geometric series of prior `ConsensusHash` values), and will continue to be derived from the set of burnchain operations selected in its burnchain block, but now it will _also_ be derived from a bitvector that represents the availability of prior PoX anchor blocks.  So, all nodes that process the same view of the Bitcoin chain _and_ have the same PoX anchor blocks will derive the same `ConsensusHash` values.  The PoX bitvector will be maintained by the PoX database, and will be fed into the `ConsensusHash::from_ops()` method when processing a burnchain block's sortition.

Instead of deriving the index block hash for a Stacks block from its burnchain block's header's hash and its header's hash (via `StacksBlockHeader::make_index_block_hash`), it will now be derived from its burnchain block's `ConsensusHash` and its header's hash.  This way, a single burnchain block can have many different Stacks blocks, but a single burnchain block can have at most one Stacks block within a given PoX fork.
