### ISSUE TITLE
BNS: namespace registrar contract

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1801]
Now that we have traits, would it be possible to create a namespace such that the namespace creator can designate a registrar contract that must handle all name operations?  This would give developers a lot of flexibility in defining registration rules (so we don't have to think of them all up front).  What do you think @lgalabru?

**Comment by jcnelson** [comment]
* This would affect the `contract-call` transactions -- you'd need to concretize the registrar contract.
* The namespace would need to deny the `contract-call` unless the namespace-creator-determined registrar contract was used

**Comment by hozzjss** [comment]
So instead of the replicated db this would be on-chain data for subdomains? how different is this going to be from the current implementation? it is much better to have a contract holding this state as a registrar so that you won't need to maintain a server or are we just talking about names or namespaces here, if there's a spec or a proposal for this could someone point me in the right direction :grin:

**Comment by jcnelson** [comment]
Hey @hozzjss, this only applies to on-chain names.  Off-chain names will work as before -- they'll remain off-chain, with a separate registrar process for generating and submitting `NAME_UPDATE` transactions.  There's no spec yet for on-chain registrars.

**Comment by jcnelson** [comment]
For feature-freeze, the only thing we need to make sure happens is that we can whitelist a principal that can do name operations.  That whitelisted principal would be the registrar.
