### ISSUE TITLE
Stacking: BTC reward details

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain#1822]
As discussed [in the "Stacking needs" document](https://paper.dropbox.com/doc/Stacking-needs-for-Blockchain-API--A6EScHX2fuQemAiFD1AjLhLrAQ-sZ40khxoJpRJh8cPQ4N8A), it would be great to get access to the following stacking rewards details: 
- Lifetime earned BTC
- The last cycle earned BTC

cc @markmhx

**Comment by jcnelson** [comment]
We discussed this in the blockchain meeting, and the consensus is that instead of exposing this information as a RESTful API on the node, we'll emit block-commit events which log how much BTC was sent to each PoX address.  Then, the side-car will be responsible for gathering these events and calculating a materialized view over all PoX BTC balances.

**Comment by agraebe** [comment]
fyi @zone117x

**Comment by zone117x** [comment]
The API exposes BTC rewards in a few endpoints here: https://blockstack.github.io/stacks-blockchain-api/#operation/get_burnchain_rewards_total_by_address (ones starting with `/extended/v1/burnchain/rewards`). Looks like we can close this issue?
