### ISSUE TITLE
Sponsored tx origin verification using standard auth flags

### ISSUE THREAD

**Issue by reedrosenbluth** [blockstack/stacks-blockchain#1826]
@jcnelson is this a typo, or is there a reason for this?

https://github.com/blockstack/stacks-blockchain/blob/c3d640a0360159c7494596f33d3bc874e6a07615/src/chainstate/stacks/auth.rs#L885

**Comment by jcnelson** [comment]
Where's the supposed typo?

**Comment by zone117x** [comment]
Multisig transactions are no longer being accepted by the core-node. Unclear if it's a regression in stacks-transaction-js lib or core-node. Reference issue https://github.com/blockstack/stacks-transactions-js/pull/109#issuecomment-676798745
 Error from core-node:
```json
{
  "error": "transaction rejected",
  "reason": "SignatureValidation",
  "reason_data": {
    "message": "Signer hash does not equal hash of public key(s): 9773d279b98a0e1388875729207fe7602cda7af5 != 31ef5ee9a226a792b93f2bfbfbc54f523eba7818"
  },
  "txid": "4a407703abe75fb5d1ad489875296d9eff52ad64bbf780b44d08d412ccb5faf9"
}
```

**Comment by reedrosenbluth** [comment]
@jcnelson I'm referring to that line being `&TransactionAuthFlags::AuthStandard` instead of `&TransactionAuthFlags::AuthSponsored`

**Comment by kantai** [comment]
> Where's the supposed typo?

It looks like in `verify_origin`, the `TransactionAuth::Sponsored` branch passes ` &TransactionAuthFlags::AuthStandard` to `origin_condition.verify`

**Comment by jcnelson** [comment]
The last time `auth.rs` or `transaction.rs` was modified would have been 5 months ago or 4 months ago, respectively.  We have lots and lots of regression tests for multi-sig transactions in `transaction.rs`, and they're all passing.  I'm going to guess this is in stacks-transactions-js.

@kantai That's not a typo.  Origin keys sign with `TransactionAuthFlags::AuthStandard` regardless of whether or not the transaction is standard or sponsored, and so the verification path must also pass in the same flags (since they're fed into the sighash calculation).  You can see this at work in the `verify()` method, where origin keys use `TransactionAuthFlags::AuthStandard` but sponsor keys use `TransactionAuthFlags::AuthSponsored` (this matches the behavior in signing).

**Comment by jcnelson** [comment]
And, it looks like it got fixed: https://github.com/blockstack/stacks-transactions-js/pull/109#pullrequestreview-473816522

**Comment by reedrosenbluth** [comment]
Thanks for explaining @jcnelson!
