### ISSUE TITLE
Contract map entries by partial key

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1881]
**Is your feature request related to a problem? Please describe.**
I would like to display the list of orders on a marketplace that belong to a user. Orders are stored in a data map with key `bidder`, `owner`, `monster-id`.

**Describe the solution you'd like**
Have an api in `stacks-blockchain-api` that allows to query a data map by partial keys, e.g. only by `owner`.

From @zone117x : 
> It would be a tremendous amount of work. the sidecar postgres db would need to essential be a mirror of the core-node MARF
and the core-node MARF is extremely complex, and extremely difficult to optimize for. The core-node would need to support it. 

**Describe alternatives you've considered**
Iterate through all transactions that change the map.

**Additional context**
https://github.com/blockstack/stacks-blockchain-api/issues/240

**Comment by jcnelson** [comment]
This is not something the Clarity VM can provide, but could be something an off-node API could implement.  Alternatively, you can structure your data-maps in your smart contracts so that matching by partial key is no longer necessary.

**Comment by friedger** [comment]
Reindexing data maps seems too expensive if I want to maintain several indexes.

Could the VM send an event when a data map was changed so that the off-node can update their index?

**Comment by psq** [comment]
> Could the VM send an event when a data map was changed so that the off-node can update their index?

@friedger this seems like it could be costly for the VM.  There are probably easier alternatives to consider:
- add a map to your contract where the owner is the key, with a list of orders as the value
- build a specialized node that extends the current vm and add a new side store to also store the key values in clear (rather than  the current implementation that uses hashes), and add an API of top of that store

First suggestion looks a lot more appealing to me...

**Comment by friedger** [comment]
Thank you for your suggestions.
