### ISSUE TITLE
PoX Proposal: Use PoX lockups to enforce recency in anchor selection

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1897]
In the current anchor block design, there's no recency limit for a PoX anchor block selection. However, Stacker's messages can be used to enforce this recency by requiring some threshold of active participant locks. To do this, we would need to add a burn height parameter to the `stacks-stx` function, such that Stackers signal the following information:

* The amount they are locking up
* The number of reward cycles they want to participate for (capped at 3 months)
* The Bitcoin block height of the first reward cycle they wish to lock up for (this is the new piece of information)

Then, when choosing a PoX anchor block, the network requires that some threshold % of liquid STX issued those messages (I think a low threshold is the right thing here, maybe 5%). This constraint, combined with the Bitcoin block height information forces PoX anchor blocks to be relatively recent, because otherwise, there would be no valid lock-ups: an old Bitcoin block height + 3 reward cycles would have expired. This, in turn, biases the miners towards forward progress because ensuring that anchor blocks are chosen makes mining slightly easier (because of the incentives of PoX vs. PoB).

**Comment by jcnelson** [comment]
I guess I'm not quite following what you mean by "recency limit".  Are you saying that, because miners could spend their prepare phase mining a non-canonical fork branched off of any arbitrarily-far-back block during reward cycle _N - 1_, they can require PoX to occur on a minority fork in reward cycle _N_?  If so, I can see why we'd want to discourage miners from doing this (and am open to modifying Stacking to get Stackers to help encourage it), but I'm curious why you don't think that miners are sufficiently incentivized by the fact that they can only cash out their STX if their blocks are confirmed by the canonical Stacks chain tip?

**Comment by kantai** [comment]
Miners are already definitely incentivized to not do this (mine on a non-canonical fork), but this allows us to use Stacking to provide some further incentivization, which also extracts some more usefulness from the process of Stacking.

**Comment by jcnelson** [comment]
This is implemented in #1937, right?

**Comment by kantai** [comment]
No, it isn't, I'm implementing most of these PoX changes separately so that the PRs will be a bit more bite sized.

**Comment by jcnelson** [comment]
Removing the "proposal" tag.  I think the consensus is that this is going forward.

**Comment by kantai** [comment]
This is closed by #1961, and has been deployed to Krypton.
