### ISSUE TITLE
Emitting stacking events for unlocks and rewards

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain#1930]
I'm working on a sample integration for Stacking and I would like to be able to obtain 3 types of stacking events:
- [x] lockups - already implemented in the node as `STXLockEvent` but I believe not yet exposed the Stacks Blockchain API
- ~~unlocks~~
- [x] rewards

The rewards paid out to the BTC address could be obtained through the bitcoin chain, but it would require me to know who transferred coins when

cc @lgalabru and @zone117x

**Comment by jcnelson** [comment]
Rewards can be done in a straightforward manner -- we'd just emit an event for the particular BTC address of the winning block-commit.

Unlocks are less straightforward.  In particular, token unlocks don't happen eagerly; they happen only once you _spend_ your tokens at some indeterminate time _after_ your lock-up period expires.  But, you probably don't need an event for unlocks (unless you specifically need an event for when a spend happens to remove the lock state from the DB, which I'm guessing is _not_ what you're interested in, since this happens lazily?), because the relevant information for determining when locked tokens become spendable again is captured in the `STXLockEvent` struct already.

**Comment by agraebe** [comment]
Right, unlocking is less important and I can  get that in other ways. Rewards are the important ones.

**Comment by agraebe** [comment]
fyi: @hstove and @kyranjamie

**Comment by kantai** [comment]
Getting reward events should be doable, but it would require a bit of effort for the node to provide the information (because the total burns of a block aren't all sent to the PoX addresses -- some will be burnt)

**Comment by zone117x** [comment]
@kantai any ETA on this feature? We have this pre-codefreeze issue blocked on it https://github.com/blockstack/stacks-blockchain-api/issues/268

**Comment by kantai** [comment]
I can slate this after wrapping up the Bitcoin Stacking operations. So either late this week or early next week.

**Comment by kantai** [comment]
Closing via #2021
