### ISSUE TITLE
PoX endpoint: time to next cycle

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain#1976]
It looks like every stacking integration would need to calculate the timestamp for the next reward cycle. The [current tutorial](https://docs.blockstack.org/stacks-blockchain/integrate-stacking#step-3-display-stacking-info) has the following formula:

```js
// how much time is left (in seconds) until the next cycle begins?
const secondsToNextCycle =
  (poxInfo.reward_cycle_length -
    ((coreInfo.burn_block_height - poxInfo.first_burnchain_block_height) %
      poxInfo.reward_cycle_length)) *
  blocktimeInfo.testnet.target_block_time;

// the actual datetime of the next cycle start
const nextCycleStartingAt = new Date();
nextCycleStartingAt.setSeconds(nextCycleStartingAt.getSeconds() + secondsToNextCycle);
```

Getting the time requires 3 API calls ([pox info](https://blockstack.github.io/stacks-blockchain-api/#operation/get_pox_info), [block time](https://blockstack.github.io/stacks-blockchain-api/#operation/get_network_block_times), and [info](https://blockstack.github.io/stacks-blockchain-api/#operation/get_core_api_info)) and a calculation that is not straight forward. 

Can we simply expose a new field `next_cycle_start_time` in the pox endpoint?

**Comment by jcnelson** [comment]
If you're trying to cut down on the number of network requests, then I have some good news:  you shouldn't need to make the block-time or pox-info calls more than once.  The block-time is constant, as is the length of each reward cycle.  You'll only need to get the updated burn block height every so often.  Come mainnet, you can remove these two one-off calls altogether, since they'll be protocol constants you can just hardcode into your client.

**Comment by lgalabru** [comment]
Addressed with https://github.com/blockstack/stacks-blockchain/pull/2459
