### ISSUE TITLE
[Feature Request] Use BNS names as contract address alias

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1989]
**Is your feature request related to a problem? Please describe.**
I would like to share my contracts with others, currently, I have to provide strings like `ST123...123.monsters`

**Describe the solution you'd like**
I would like to share my contracts like
`friedger.id::monsters`
This follows the convention of assets in contracts: `ST123...123.monsters::nft` 

_**Therefore, contract ids should use "::" instead of "."**_

**Describe alternatives you've considered**
`friedger.id.monsters` is possible as well, but more difficult to distinguish between contract name and contract address/alias

**Comment by psq** [comment]
and you might also consider adding the ability to link an id to a contract directly

**Comment by lgalabru** [comment]
I don't think this will happen, it would create a dependency between Clarity and BNS. The community should be able to pick whatever Name Service they want to go with, and if at some point, community members are building a better BNS 3.0, we don't want to slow down adoption because of an unfair integration between Clarity and BNS 2.0.
Will close.
