### ISSUE TITLE
Ability to call Stacks contracts from the Bitcoin chain

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#2060]
@kantai I won't give up that easily 😂

Opening a dedicated issue for hosting future debates.

<img width="796" alt="Screen Shot 2020-11-13 at 11 01 20 AM" src="https://user-images.githubusercontent.com/87777/99092825-ac8ece80-259f-11eb-9073-a179f3765e1f.png">

**Comment by jcnelson** [comment]
This would have some pretty severe limitations:

* The serialized contract-call payload would need to fit into 77 bytes.
* On-BTC transactions would need to be dropped in obscure, user-unfriendly ways, because we need to bound the number of on-BTC transactions that can be included in the next Stacks block.  No matter what strategy we use for this, someone's on-BTC transaction will need to get dropped in some Stacks forks and not others.  Moreover, it would be somewhat difficult to explain this concept to users who aren't already intimately familiar with the challenges of mining a blockchain on top of a blockchain like we do.
* Miners would need a way to include or exclude on-BTC transactions based on the current fee market, which is off-chain and transient state.  This means that deciding to exclude an on-BTC transactions that underpays its fee is all but impossible for a bootstrapping node to do.  So unless we somehow get miners to (a) agree on the state of the fee market, and (b) write the agreed state of the fee market and record it to the BTC chain when they mine a block (both of these are very difficult for a whole host of reasons), thereby making this information available to bootstrapping nodes, we would instead need to guarantee that an on-BTC transaction would always be mined if it could be included.  But if we do this, we would need to enforce a strict, small compute budget limitation on on-chain BTC transactions so that they'll always be cheap enough to include (which in turn severely constraints which contract-calls will be allowed to be on-chain).  This in turn leads to a bad user experience, since very few non-trivial smart contract functions would likely be cheap enough.

I don't see this happening.  If you're really worried about miners censoring your transactions, then you probably have bigger problems.

**Comment by lgalabru** [comment]
The serialized contract-call can be encoded and be stored on multiple outputs. On the UX side, I'd be surprised if even 5% of Bitcoin users understand Bitcoin script and the actual content of the outputs in their transactions. This feature has many challenges (like the fee), but I don't think that payload size, or UX are one of them.

UX would actually be motivating this feature, because it means that Bitcoin holders could natively use smart contracts and dapps, and interacting with the Stacks chain, without having to go to an exchange, buy some STX, get custody back, etc.

PoX looks already like an onchain oracle BTC <-> STX, I wonder if this can be leveraged for the fee.

**Comment by lgalabru** [comment]
Or maybe a different angle: when a user wants to send a transaction, a wallet software could build a sponsored transaction, look for a sponsor willing to pay the STX required by that transaction for a given amount of BTC, and broadcast the "stacked" transaction on the bitcoin chain + add an HTLC or something for paying the sponsor?

**Comment by jcnelson** [comment]
> UX would actually be motivating this feature, because it means that Bitcoin holders could natively use smart contracts and dapps, and interacting with the Stacks chain, without having to go to an exchange, buy some STX, get custody back, etc.

Per my second and third points, the UX of this feature would likely be _terrible_.  If you had the choice to send your transaction to the STX chain, you would do so -- it would likely be cheaper, and you wouldn't be constrained by what kinds of contract calls you can make or what fork(s) your transaction would get mined in.

**Comment by jcnelson** [comment]
Also, how big is the set of Bitcoin users who want to interact with the Stacks chain, but can't be bothered to acquire STX?  Seems like an awful lot of work to build a transaction-processing method with a worse UX, just to acquire users who can't be bothered to use the system in the first place.

**Comment by friedger** [comment]
One narrow, very specific use case of the feature would be wrapped Bitcoin. Sending BTC to a certain Bitcoin address would trigger the minting of wBTC on the Stacks chain, the bitcoin sender would receive STX on the corresponding Stacks address. This could work also the other way around.
