### ISSUE TITLE
Saving up to 25% on BTC txn fees

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#2071]
I spent some time checking BTC transactions emitted by the stacks node today, and while testing a few explorers I noticed this on one of them.
Is this a lead we want to explore / push?

<img width="992" alt="Screen Shot 2020-11-17 at 11 14 37 PM" src="https://user-images.githubusercontent.com/87777/99482798-c0815a00-292a-11eb-87e4-ca13cdd6472d.png">

**Comment by jcnelson** [comment]
Maybe in 2.1.  Not sure we have time to implement full native segwit support for outputs where we need to extract an address (not even sure how'd we'd go about that in the first place, since we depend on the interchangeability between bitcoin and stacks addresses).  We can already support segwit-p2sh block-commits though.

**Comment by jcnelson** [comment]
Closing in favor of #2586
