### ISSUE TITLE
Atlas: garbage collect uninstantiated attachments

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#2135]

**Comment by jcnelson** [comment]
I think there are a few things that will need to happen here:

* The Atlas DB should only accept an attachment for a `ContractCall` transaction type.  Moreover, the API should require that the `ContractCall` transaction calls into one of the whitelisted smart contracts for which Atlas stores data.

* The Atlas DB needs to bound the maximum number of uninstantiated attachments that can exist at once (this number can be configurable).  If the DB permits only up to _N_ uninstantiated attachments, and the _N+1_-th uninstantiated attachment arrives, the DB should evict one of the older uninstantiated attachments.  It can simply evict the oldest.

* The Atlas DB should have a "garbage-collect" method that gets called once every _X_ minutes or once every Stacks block arrival (whichever takes _more_ time to pass) that just `DELETE`s any uninstantiated attachments that are older than a certain age (this value can be configurable, but should probably be at least 1 hour).  The _X_ minutes can be a hard-coded constant, since it's only necessary to ensure that a bootstrapping node doesn't spend all of its time calling `DELETE` unnecessarily.

**Comment by lgalabru** [comment]
Address with https://github.com/blockstack/stacks-blockchain/pull/2204
