### ISSUE TITLE
Detecting miner commitments in window amid invalid commitments

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2141]
Currently, the miner commitment windowing requires that each linked UTXO be between valid commitments, however, this may end up punishing an honest miner when one commitment "misses" the intended Bitcoin block, e.g.,

commit 1 -> goes in burn block 1
commit 2 -> goes in burn block 2
commit 3 -> goes in burn block 3
commit 4 -> goes in burn block 5
commit 5 -> goes in burn block 5

"commit 4" _isn't_ a valid block commit, and because of that, the miner is significantly punished -- not only is that commitment lost, but "commit 5" doesn't get to claim commits 1->3 as part of its window.

Fixing this would require more leniency in the way we enforce UTXO chaining across the commitments.

**Comment by jcnelson** [comment]
Hmm, what if we had a way for a block-commit to indicate its targeted burnchain block?  Then, we could automatically detect this bumping behavior and _not_ punish a miner that tried to issue the block-commits correctly.  Regardless of how the bumping happens, it will always be the case that:

* commit _i_ will be mined before commit _i+1_ in the transaction history, and
* if commit _i_ is mined in burn block _b_, then commit _i+1_ may be mined in any burn block _b + k >= b_

So to calculate the sortition weight for block commit _i_ sent by miner _M_, all we'd need to do is search back 6 burn blocks and find the last 6 block-commits _M_ sent, and verify that each of these 6 block-commits targeted a unique burn block in the last 6 burn blocks (even if they didn't get mined in them).  If this was the case, then miner _M_ was trying to be compliant and should be allotted a _mean(median - min)_ burn weight.

How can we let miners target a burn block?  We'd only need two bytes (really only 11 bits), with which we can encode the index into the reward cycle's reward set that was targeted (which can be between 0 and 2000).  From there, we can calculate which burn block the block-commit had meant to be mined in, and validate its burn/PoX outputs against that burn block (which we will always have already processed or will be in the middle of processing, per the above two invariants).

Where are we going to get 11 bits?  We have 7 bits remaining in the block-commit structure's `memo` field (I'm using one of them to solve #1805, by which miners indicate that they're doing PoB because they don't know the anchor block even though one was selected).  We can borrow 4 more bits from the VRF seed, and just treat the lowest 4 bits of the VRF seed as always being 0, and only comparing the hash of the VRF proof from a Stacks block against the remaining bits (which I don't think will significantly impact security -- going from a 32-byte hash to a 31.5-byte hash).

What do you think?

**Comment by kantai** [comment]
I think that could work, but it would require that we track a new block commit state, which is something like "invalid, but off by one" and store block commits that are in that state (currently, we only store in the sortition db block commits that are valid).

I'm starting to think that we should perhaps relax our "no txindex" requirement for bitcoind. The txindex adds less than a 10% storage overhead to bitcoind, and doesn't significantly slow processing. The advantage of doing this is that we could solve this problem (with the upside that UTXO chaining is no longer necessary) _and_ eliminate the necessity of `PreStxOp`.

**Comment by muneeb-ali** [comment]
@kantai @jessesoslow Is it worth revisiting the earlier median/mean discussion as a metric for smoothing function in light of this new potential corner case where an honest miner misses a block because the transfer went into another block and wasn't counted? I know we don't want to make needless changes at this stage but the code change might be small but potential impact on miner behavior can be quite significant.

**Comment by jcnelson** [comment]
> I'm starting to think that we should perhaps relax our "no txindex" requirement for bitcoind. The txindex adds less than a 10% storage overhead to bitcoind, and doesn't significantly slow processing. The advantage of doing this is that we could solve this problem (with the upside that UTXO chaining is no longer necessary) and eliminate the necessity of PreStxOp.

How would having a `txindex` solve this problem?  Transactions can still be bumped into different blocks than they were meant for, so UTXO-chaining or not, you're still going to need to find a way to give miners credit for trying to include their block-commit transactions.  Also, `getrawtransaction` is a _very_ slow RPC call -- it takes about as long to fetch a single transaction from the `txindex` over RPC as it does to fetch a _whole Bitcoin block_ from the p2p interface.

**Comment by kantai** [comment]
> How would having a txindex solve this problem? Transactions can still be bumped into different blocks than they were meant for, so UTXO-chaining or not, you're still going to need to find a way to give miners credit for trying to include their block-commit transactions in the right blocks even if they miss them. Also, getrawtransaction is a very slow RPC call -- it takes about as long to fetch a single transaction from the txindex over RPC as it does to fetch a whole Bitcoin block from the p2p interface.

We would be able to associate each miner commitment with a Bitcoin address by validating that the first input's spent UTXO is a standard output.

**Comment by kantai** [comment]
> @kantai @jessesoslow Is it worth revisiting the earlier median/mean discussion as a metric for smoothing function in light of this new potential corner case where an honest miner misses a block because the transfer went into another block and wasn't counted? I know we don't want to make needless changes at this stage but the code change might be small but potential impact on miner behavior can be quite significant.

I think it probably is -- perhaps something less punitive than `mean of min and median`, like the `mean of second-min and median`, would be preferable. But I think the way we calculate windowing would still need to be updated, so that we can at least continue to associate the valid commitments with each other.

**Comment by jcnelson** [comment]
> We would be able to associate each miner commitment with a Bitcoin address by validating that the first input's spent UTXO is a standard output.

You can already do this with my proposed change, because you'd still store a block-commit even if its target reward cycle index doesn't match the reward cycle index you'd calculate from the burnchain height.  A block-commit is valid for storage if it's either PoB, or if it's PoX _and_ its PoX output addresses match the block-commit's target in the `OP_RETURN`.  If the target happens to also match reward cycle index corresponding to its burnchain block, then it's also valid for being used to calculate the sortition distribution. Otherwise, it cannot be used to win a block -- the `make_min_median_distribution()` function will just ignore it.  But regardless, when calculating some function over the last _N_ block-commits sent by this miner (mean-min-median or whatever), you'd organize block-commits by their target index instead of their burnchain-derived index, and you'd use the block-commit's true BTC sent as before.

**Comment by kantai** [comment]
> You can already do this with my proposed change, because you'd still store a block-commit even if its target reward cycle index doesn't match the reward cycle index you'd calculate from the burnchain height. A block-commit is valid for storage if it's either PoB, or if it's PoX and its PoX output addresses match the block-commit's target in the OP_RETURN.

Yes -- I think both this proposal and `txindex` support similar processes. But with the `txindex`, we'd be able to just associate a block commit with an address, not needing to do any kind of chain-resolution, and the miner would not need to be carefully chaining UTXOs either. Of course using the `txindex` (even ignoring the RPC cost) isn't perfect either -- we wouldn't be "counting" the missed-but-would-have-been-legal block commits in the smoothing function, while in your proposal, we're able to.

Your proposal, though, would add a lot of complexity to an already complex process -- we'd need to update the sortition processing to do the following (let's say we use 3 bits for this):

* When processing a `LeaderBlockCommit`, if the `goal_burn_height % 8 != actual_burn_height % 8`, then look up the sortition processed at that goal burn height (at most 7 sortitions in the past), and invoke `.check()` on that operation with a sortition handle TX at chaintip = goal burn height (with the PoX info re-calculated at that burn height). If this check succeeds, mark this LeaderBlockCommit as "accepted", but perhaps as a new `OperationType::MissedBlockCommitOp` or pass it through the various sortition processing methods as an additional argument `missed_commits`.
* Store these missed commits in a new sortition db table, with the `SortitionId` field set to their _goal_ sortition id, not the burn block that actually included them.
* When computing the `BurnSamplePoint` distribution, in addition to fetching the LeaderBlockCommits from the miner smoothing window, we fetch missed commits associated with those same blocks (and any missed commits in the current block), and include them in the calculation of the distribution.

I'd estimate this as like a ~1 week undertaking, and so I wonder how concerned we are about this -- do we think that miners will frequently be unable to get their commits included in the targeted bitcoin block? And if they can't, is alleviating this punishment worthwhile (their block commit is already invalid, so they are forfeiting any possibility of a coinbase already)?

**Comment by jcnelson** [comment]
Just had a call with @kantai about this.  Recall that the purpose of UTXO-chaining and taking the mean-min-median of the last _N_ block-commits is to discourage miners who can discount-mine from doing so.  This smoothing function requires miners to mine at a more consistent rate in order to have a shot of winning a block race.

We can solve this problem through other means that will take less engineering time up-front.  I think the consensus going forward is:

* Use a smoothing function that only considers the _current_ burnchain block's block-commits.  This would remove the need to do UTXO-tracking altogether, and it would still encourage miners to mine at a consistent rate (instead of mining only when their own 
* Monitor the chain for discount-mining behaviors, and introduce _via a soft-fork_ the ability for miners to orphan blocks produced by malicious miners that don't mine at consistent BTC-transfer levels.  Recall that miners can choose which block they build off of.  We can modify the chainstate-processing logic to never consider a descendant of a block whose miner wasn't mining consistently enough for our purposes.  This is a backwards-compatible change, since if the majority of the mining power orphans blocks produced this way, then the rest of the network will not consider them canonical (which ensures that miners who mine inconsistently cannot profit from doing so -- their earned STX would be rendered worthless).

**Comment by kantai** [comment]
Yep -- I think we may be able to adopt a smoothing function that alleviates this, while still doing some windowing, e.g.:

```
f = min ( current_block_burn, mean( current_block_burn, median(block_burn over 5 block window)))
```

**Comment by jcnelson** [comment]
Can we close this now?

**Comment by kantai** [comment]
Yep
