### ISSUE TITLE
Refactor function names in Costs contract

### ISSUE THREAD

**Issue by reedrosenbluth** [blockstack/stacks-blockchain#2185]
Refactor function names in costs.clar contract to use dashes instead of underscores

**Comment by njordhov** [comment]
Yes! When I originally [proposed](https://github.com/blockstack/stacks-blockchain/issues/1794#issuecomment-675076057) using a Clarity contract for the cost-assessment of Clarity functions, I deliberately used an underscore in the function name, to distinguish the name of the applicable clarity function (`get`):

```
(define-read-only (cost_get (num-fields int))
  (+ (* a (log num-fields)) b))
```

 It was not intended to replace the kebab-case convention. Instead, it is a naming used in lisp compilers when meta-referencing lisp functions. In this case indicating it calculates the cost of the `get` function. A better example would be `cost_as-max-len` for the cost of the `as-max-len` native Clarity function. 

But it turns out most functions in `costs.clar` don't actually reference the Clarity name of native functions, making this naming scheme irrelevant.
