### ISSUE TITLE
peer connection backoff not allowing nodes to sync 

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/stacks-blockchain#2201]
My node is having an extremely difficult time syncing and remaining in sync with the chain tip because of this.  It catches up, then falls back again. The backoff retry setting quickly ramps up to high durations up to 60 seconds: 
https://github.com/blockstack/stacks-blockchain/blob/c1b74ec457dcff2909fdbac49000f4b29a55f49f/src/burnchains/bitcoin/network.rs#L174

**My config:** Ubuntu 20.04 VM node running in Brazil via 4G connection, running the testnet miner (Daemon bot) output showed 
`ERRO [1608567440.603344] [src/burnchains/bitcoin/network.rs:208] [ThreadId(1)] Failed to connect to peer 35.245.94.44:18444: connection to peer could not be (re-)established
WARN [1608567440.603433] [src/burnchains/bitcoin/network.rs:222] [ThreadId(1)] Connection broken; retrying in 60 sec...

Could be connection problem on my end but **should poorly performing nodes be quickly blacklisted?**  Otherwise good nodes could be somewhat DDOS'ed by bad nodes either on accident or by a bad actor?

If 4G sometimes does not handle a lot of simultaneous connections **could we use a config parameter like MAX_CONNECTIONS to limit it?**

_Originally posted by @fluidvoice in https://github.com/blockstack/stacks-blockchain/issues/2198#issuecomment-749052660_

**Comment by fluidvoice** [comment]
I'm wondering if the backoff setting should be an external config param?  So that people can set it to bette suite their network performance.  It seems to be the backoff ramps up quickly to 60 seconds.  And I think - but not sure exactly - that if it just continued to retry every 3 seconds that it would function better with my 4G connection.  Why it keeps losing connection is a mystery though and various others had the same problem during the Testnet mining period.  My node is having a hard time remaining in sync with the chain tip because of this.  It catches up, then falls back again.

https://github.com/blockstack/stacks-blockchain/blob/c1b74ec457dcff2909fdbac49000f4b29a55f49f/src/burnchains/bitcoin/network.rs#L222

**Comment by fluidvoice** [comment]
should poorly performing nodes be quickly blacklisted?  Otherwise good nodes could be somewhat DDOS'ed by bad nodes either on accident or by a bad actor?

**Comment by jcnelson** [comment]
Hi @fluidvoice,

The code in question attempts to talk to a given Bitcoin node, and if the Bitcoin node doesn't reply in a timely fashion, the Stacks node will try again at exponentially-increasingly large intervals [1].  This should be serving to limit the load on the remote Bitcoin node.

In your particular case, it looks like you're hitting the singular Bitcoin regtest node that PBC is running, and it's quite possible that due to the ongoing mining competition by Daemon Technologies, it's simply under a lot more load right now than it would be.  Going forward, it's expected that Stacks node operators will either use their own Bitcoin mainnet nodes (i.e. if you're a miner and need high uptime), or use a public Bitcoin node somewhere.

It's also possible that your ISP is rate-limiting you, or introducing high latency.  I don't know very much about what kinds of traffic-shaping your Brazilian telco might do, but having run Stacks 1.0 nodes over a 4G cellular connection myself, the comparatively-higher latency from the cellular connection alone may be the cause of the delay error.

[1] https://en.wikipedia.org/wiki/Exponential_backoff

**Comment by fluidvoice** [comment]
@jcnelson I recently synced my own Bitcoin full node with this same 4G connection and I use it for everything else.  Is a Stacks node more demanding or less forgiving of latency than a Bitcoin node?  If it's a single server then that makes sense as this same problem has been reported my multiple other people.  Thanks.
