### ISSUE TITLE
Delegate transaction from an address with unlocked STX

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/stacks-blockchain#2251]
What's the current behavior if an address A that has say 50 unlocked STX and 50 locked STX delegates to address B for participating in stacking?

Do 50 STX get delegated (given they were unlocked) and remaining will require a new delegate transaction once they unlock OR are all 100 STX delegated to address B but only the unlocked ones can participate in any given reward cycle?

This came up in a discussion. Thanks!

**Comment by jcnelson** [comment]
An address can have at most one active PoX lock-up on it.  Once the lock is created for a given amount of STX, it cannot be altered until the STX unlock.  If you lock up tokens by delegating, the lock is still instantiated on _your_ address.

If you have 100 STX, and you lock 50 STX through a delegate, you'd have 50 not-locked STX left that you could spend.  If you wanted to then lock those 50 STX as well, you'd need to first transfer them to a new address, and then you can lock them from there.

**Comment by muneeb-ali** [comment]
Got the one active PoX lock part.

My question is about other types of locks. If there are 60 STX under a separate lock (say vesting type lock) and 40 STX under no lock. My assumption is that in this example a maximum of 40 STX can be locked for PoX through delegate. And when more STX unlock, say another 10 STX then a separate delegate transaction is needed on the newly unlocked 10 STX. (Or you overwrite the last delegate at the end of a reward cycle and do a new 50 STX delegate locking.)

**Comment by jcnelson** [comment]
> My assumption is that in this example a maximum of 40 STX can be locked for PoX through delegate.

That's correct.  If your tokens are still locked up from a previous token sale, you can't do anything with them.  They aren't even counted as part of the `stx-liquid-supply` variable in Clarity (this is intentional -- keeping this as low as possible also lowers the minimum lock-up for PoX).

> And when more STX unlock, say another 10 STX then you need to first move them and then do a separate delegate transaction. (Or you overwrite the last delegate at the end of a reward cycle and do a new 50 STX delegate locking from original address.)

If the delegate has already locked your STX, you'd need to first move them to a new address.  But if the delegate hasn't locked your tokens yet, you can just update the amount of STX you want the delegate to lock (since there's a window of time between when you delegate your STX and when the delegate executes the lock-up).
