### ISSUE TITLE
Microblock vs. Anchor Block Limit Billing

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2256]
Currently, we bill the cost of confirming microblocks to the parent, by setting the cost so far to the parent block's cost:

https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/db/blocks.rs#L4193

And then resetting to zero after the microblocks are processed:

https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/db/blocks.rs#L4282

This imposes a block limit on the parent's anchored block + microblocks, and then a separate limit on the current anchored block.

I think this is the correct behavior.

Related to this is the behavior of the "cost-voting" contract. Imagine the following scenario:

```
A -> a -> B -> ...
```

where `A` is an anchored block and `a` is the microblock stream that `B` confirms.  If a new cost function is confirmed in block `A`, the current implementation will evaluate `A` with the prior cost function, and evaluate `a` and `B` with the new cost function.

Is this all the behavior that we think is desirable?

**Comment by jcnelson** [comment]
> I think this is the correct behavior.

I think so too.  While it is the case that, as a miner, you can produce a microblock stream that exceeds your compute budget, it is also the case that no one will ever confirm the part of your stream that goes overbudget.  This is true even if someone _wanted_ to confirm it.  A miner that confirms a parent block and microblock stream that exceed the block limit would cause block-processing to fail for their block in all other nodes.  Specifically, the error path here would be taken when processing the child block's confirmed microblock stream, once it goes overbudget: https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/db/blocks.rs#L4255.  So, a miner that confirms an overbudget parent anchor block and parent microblock stream effectively orphans their block, with no penalty to the network (since processing stops once the budget is marginally exceeded).

> Is this all the behavior that we think is desirable?

I think this approach is at least _fair_, which is sufficient to make it desirable for me.  If you're a miner, and you produce `A`, you will know (or ought to know) that the cost function takes effect at the end of `A`.  Through no additional action of your own, the miner code should automatically apply the new cost function when it starts to consider transactions for inclusion in the tail microblock stream (we'll want to add a unit test for this at least).  So, even though it may seem odd that the cost function takes effect _during_ your tenure, it's something the miner is capable of handling gracefully.

**Comment by kantai** [comment]
Closing -- this behavior is both the intended behavior and what is currently implemented.
