### ISSUE TITLE
When do we expect the Blockstack DID Method Specification to be finalized 

### ISSUE THREAD

**Issue by Muhammad-Altabba** [blockstack/stacks-blockchain#2353]
The Blockstack DID Method Specification (https://github.com/blockstack/stacks-blockchain/blob/stacks-1.0/docs/blockstack-did-spec.md) is last updated one and a half years back, and it still in draft mode.

> This is a draft document and may be updated, replaced or obsoleted by other documents at any time.

When do we expect it will be finalized? Or at least to be updated to be according to W3C DID specification?

Thanks,

**Comment by jcnelson** [comment]
This isn't the right repository for this issue.  You'll want to post to https://github.com/blockstack/stacks-blockchain-api, since this service has subsumed the naming and identifier responsibilities that were originally handled by the Stacks blockchain.

> When do we expect it will be finalized? Or at least to be updated to be according to W3C DID specification?

Whenever someone steps up and does the work.  PRs are welcome :)
