### ISSUE TITLE
Mempool transactions `accepted_at` different forks are not considered

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2394]
Transactions that received into the mempool at block `A`, but block `A` is "forked away", will not be considered for mining by the current miner implementation because those transactions will not appear in the miner's walk.

However, such transactions are viable for "replace-across-forks", such that if the transaction is rebroadcasted (not re-signed or fee upgraded), the miner will replace the existing tx in the mempool.

The rationale for this behavior is that the mempool admission checks that succeeded in one fork may have failed in the other. It isn't clear how large of a problem this behavior is currently (I think #2389 is a bit of confounding variable at the moment), and I think workarounds would be fairly simple _and_ effective, so this is probably a low priority change.

**Comment by pavitthrap** [comment]
Fixed in `develop`

**Comment by pavitthrap** [comment]
For #2393, I decided to implement the strict nonce-order with the following approach: (1) get a list of (consensus hash, block header hash) pairs that correspond to the last 256 blocks (or less) of the canonical chain tip, (2) select tx's in the mempool that have a consensus hash/ block header hash pair that correspond to one of the pairs in the list I created (used inner join for this), (3) order these tx by origin_nonce then timestamp, (4) query for the next "batch" of tx's to run the todo function on based on current nonce & timestamp, ordered by sponsor_nonce. 

However, I kind of am rethinking this approach based on this issue (which I was originally planning on implementing after I submitted this PR, but now I think I should do it at the same time). For a combined approach (doing nonce-order as well as including txs from different forks), I think I could do the following: (1) select all tx's with height > curr_height-MEMPOOL_DEPTH, and then (2), (3) correspond to (3), (4) from the steps above. Are there issues with how I select tx's for the second approach?

@jcnelson @kantai thoughts?

**Comment by kantai** [comment]
> However, I kind of am rethinking this approach based on this issue (which I was originally planning on implementing after I submitted this PR - #2514, but now I think I should do it at the same time). For a combined approach (doing nonce-order as well as including txs from different forks), I think I could do the following: (1) select all tx's with height > curr_height-MEMPOOL_DEPTH, and then (2), (3) correspond to (3), (4) from the steps above. Are there issues with how I select tx's for the second approach?

I would be in favor of this approach -- I think basically what it would mean is:

1. Nodes accept transactions into their mempools based on their most up to date chain view.
2. Miners evaluate any transactions in their mempools.

The difference between that and the current implementation is that there are some transactions which may have been valid in a reorg'ed fork, but are not valid in the current fork, that miners will attempt to mine (and fail to). I don't think this would add much new burden to Stacks nodes, and it would definitely simplify the operation of the mempool.

**Comment by jcnelson** [comment]
In a naive miner, I don't even think it's important to consider whether or not a transaction was valid in a non-canonical fork but is invalid now (or vice versa).  In both cases, the miner should attempt to mine an origin account's transactions in ascending nonce order, starting from the origin account's current nonce at the canonical chain tip (plus one).  It doesn't really matter what the transaction's associated consensus hash and Stacks block hash are.  The miner will skip transactions with stale nonces, and if it determines that a transaction is invalid when applied against the current chain tip, it will stop processing all future transactions for that origin account.

But, how should an origin account's client react to the case where a sequence of its transactions get rendered un-mineable by a Stacks chain reorg?  I don't think it's desirable or fair to ask them to RBF these transactions, since setting a higher fee isn't actually doing anything for the sender.  This is because two transactions with the same origin and nonce but destined for conflicting forks should, themselves, not be considered by the mempool to be conflicting (and thus not requiring RBF).  So, both transactions should be included if the mempool admission logic can reason that they'd be mined in separate forks.

I think in order to handle this case, the mempool walk algorithm would look like this instead:

1. Find the `(consensus_hash, block_header_hash)` pairs for the last MEMPOOL_DEPTH blocks on the canonical fork
2. Produce a row iterator for all transactions whose heights are within the last MEMPOOL_DEPTH blocks.  You'd want the iterator to yield all transactions for a given origin address in ascending nonce order, and I think you'd want to start with the origin address whose sequence of as-of-yet-unmined transactions will produce the highest combined STX fee (and proceed through origin addresses in descending collective unmined fee order)
3. When iterating through transactions, if you find a sequence of two or more transactions from the same origin that have the same nonce but different `(consensus_hash, block_header_hash)` tips, first try to apply the one (if any) that corresponds to a pair in the list you produced in (1).  If no such transaction exists, then proceed to try the remainder in random order until one succeeds.  If none succeed, then proceed to the next origin address.

What do you think @kantai @lgalabru @pavitthrap?

**Comment by pavitthrap** [comment]
Fixed in #2514
