### ISSUE TITLE
Performance: `PeerNetwork::can_download_microblock_stream` is prohibitively slow

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2405]
The downloader in `develop` will make every effort to _not_ re-download the same data twice.  For microblock streams, this means verifying that (a) the parent anchored block exists, (b) the child anchored block exists, and (c) each microblock in-between them exists.  Part (c) is expensive -- it's one SQL query _per microblock_.

We can omit (c) in the happy path by simply checking that the child in (b) is processed and not orphaned, since this proves that the microblocks were present (or will never need to be fetched for this child).  We can omit (c) in the unhappy path by having the downloader remember in RAM that it did the expensive check already for the child in (b), and that this stream is already known to be present for that child block.

**Comment by kantai** [comment]
PR #2411 speeds up this process (at least on SSD, I'd guess even more so on spinning disk) in two ways:

1. A lot of the overhead of the downloader was being spent fetching the block availability, which itself was suffering from the problems described in #2406, so just apply the wins from addressing that.
2. Add a sqlite index in the sortition db's snapshots table on the winning block hashes, because the downloader queries that for each block -- in profiling, that was the majority of the sqlite cost (i.e., unindexed scans). The remaining time in the tests appears to actually be IO from reading in the stacks headers.

We should see if just those changes address the performance issues in the downloader enough to avoid modifying any of the logic of the checks.

**Comment by jcnelson** [comment]
Closed by #2411
