### ISSUE TITLE
Ability to recover working_dir: handle schema and data migrations

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#2434]
I think the "only" work remaining on that epic, is the ability to handle db migrations: if a working_dir was created with version `2.0.4`, all the db will be version `1`. If `2.0.5` is introducing a schema's change, we need to be able to apply the change on the schema + data migration when required.

I started writing some code, but I think it would be more reasonable to delay this project to `2.0.6` so that I can focus on Atlas.

**Comment by jcnelson** [comment]
I don't think we need to worry about database migrations right now.  Just the ability to stop/start the node safely is a huge win :+1:  To be honest, I see migrations being handled by separate set of tools -- we'd make a tool to migrate from version 1 to 2, one to migrate from 2 to 3, etc., and keep all that logic outside of the node (since it makes it easier to test and trouble-shoot).  We can also write it as shell scripts or even raw SQL files :3
