### ISSUE TITLE
Miner stopped mining while having sufficient BTC balance

### ISSUE THREAD

**Issue by MaksimalistT** [blockstack/stacks-blockchain#2443]
**Describe the bug**
Miner stoped mining with error message 
WARN [1613281868.454811] [testnet/stacks-node/src/neon_node.rs:1654] [relayer] Failed to submit Bitcoin transaction
while BTC wallet had balance sufficient for 5+ commits
after putting additional BTC to the wallet, mining resumed

**Steps To [Reproduce**](url)
Fill BTC wallet to be sufficient for >6 commits, wait while there is BTC left for 5 commits

**Expected behavior**
Miner doesn't stop mining while there is enough balance for at least 1 commit

**Environment (please complete the following information):**
 - OS: Amazon Linux
 - Rust version: rustc 1.49.0 (e1884a8e3 2020-12-29)
 - Stacks-node 2.0.4

**Additional context**

**Comment by jcnelson** [comment]
Hey, thanks for reporting this!  Do you have some additional debug logs that would indicate which UTXOs are under consideration?  One way this might happen is if, for example, the UTXO set is so fragmented that it becomes intractable to produce a block-commit transaction.

**Comment by MaksimalistT** [comment]
Hi, don't have debug logs
>the UTXO set is so fragmented that it becomes intractable to produce a block-commit transaction.
could you please elaborate on this, what to understand it better
thanks

**Comment by MaksimalistT** [comment]
Hi, @jcnelson 

> the UTXO set is so fragmented that it becomes intractable to produce a block-commit transaction.

is there a way to check this for the wallet?
it's very important to know at what point miner will stop mining, as now it happens unexpectedly

**Comment by jcnelson** [comment]
Hi @MaksimalistT,

The miner currently doesn't try and consolidate UTXOs while it mines; it just uses the biggest one it can find for your address.  You can see this in action here: https://www.blockchain.com/btc/tx/aea5023498345761909d166cfedd3d778f2e045220e4eb8d7d43d552c5c6964d. The reason for this is because it's trying to keep your transaction as small as possible in order to (1) minimize the RBF fee you'd have to pay to re-mine an in-flight block if you discover a better chain tip to mine off of, and (2) minimize the transaction fee you'll pay to Bitcoin miners.  Most people will periodically create a single large UTXO to re-fill their running miner, and take care of consolidating the smaller depleted UTXOs out-of-band as needed.

Most Bitcoin wallets will let you consolidate your UTXOs into a single large UTXO.  I think this is what just happened with your miner's address? https://www.blockchain.com/btc/tx/749a28a963b1f0a6a575333465610737284144e8f42c3228a3a129950a1a9455

**Comment by MaksimalistT** [comment]
Got it, so i need to review UTXOs and consolidate those that are smaller than miner commit
could you please give an advice what is the best way to do it?

**Comment by jcnelson** [comment]
You could use Electrum for this -- you'd import your private key in and have it generate a transaction to consolidate your UTXOs.  You could set a low fee on this if it's not a super-high priority (the transaction will be somewhat big, since it needs to gather lots of small UTXOs).

**Comment by MaksimalistT** [comment]
What i have to do in electrum? select coins and send then in one transaction to the same wallet?
