### ISSUE TITLE
Error when calling `(fold concat ...)` example from docs

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#2512]
In the [Clarity language reference](https://docs.blockstack.org/references/language-functions#fold), one of the examples for `fold` is:

```clar
(fold concat "cdef" "ab")   ;; Returns "fedcab"
(fold concat (list "cd" "ef") "ab")   ;; Returns "efcdab"
```

However, when calling this with `clarity-cli`, I get the error "Analysis error: use of illegal / unresolved function 'concat".

This happens whether I'm writing a contract and using `clarity-cli`, and also when entering just that line into a [Clarity REPL](https://lgalabru.github.io/clarity-repl/).

I'm not sure if this is a bug in Clarity, or a valid error, and the example should be removed from the docs. It seems like a perfectly valid thing to do.

**Comment by jcnelson** [comment]
The error is the correct thing to do; the example is bad.

The `concat` function is a "special" function, making it ineligible for `fold`.  This is because it takes `(buff M)` and `(buff N)` as its input types, and returns type `(buff (+ M N))` (where `M` and `N` are inferred by Clarity at analysis time).  This is what makes `concat` "special" -- in Clarity, you can't define a function with a parameterized type signature like this.

Specific to `fold`, `fold` must take a function that takes two instances of type `A` and returns an instance of type `A`.  In Clarity, `(buff M)` and `(buff N)` are different types if `(not (is-eq M N))`.  `(buff (+ M N)` is always going to be a different type than `(buff M)` and `(buff N)` unless either `M` or `N` is 0.

**Comment by jcnelson** [comment]
Also, these code examples should be getting run in the CI process, but this particular test would be rejected by the static analysis code path, not the interpreter.  So the doc tests need to be fixed to catch this sort of thing, it seems.

**Comment by hstove** [comment]
Thanks for the info! It all makes sense.
