### ISSUE TITLE
#Stacking/Stack-stx The unlock-burn-ht calculations are incorrect for Stackers locking during the prepare phase of any cycle 

### ISSUE THREAD

**Issue by HariniRajan397** [blockstack/stacks-blockchain#2542]
**Issue context**

  Ideally, the Stackers locking their STX before the prepare phase of any cycle is not eligible for POX rewards for that cycle. But the unlock-burn-ht calculations are looking incorrect, if any Stacker locks the STX (invokes stack-stx) during prepare phase of any cycle. 

**Scenario** 

   I locked the STX amount during the prepare phase of cycle 2. 
 Cycle 2 begins at #670150
 Cycle 2 prepare phase from #670150 to 670250 
  Stacks locked at #670,169 - This is within prepare phase. 
  Stacks locked period : 3 cycles. 

**Expected Result**
  Ideally, since I locked after #670150, I would expect I am not eligible for cycle 2 but since I locked for 3 cycles, I am eligible for Cycles 3, 4, 5 and my unlock-burn-ht will be at the end of prepare phase of cycle 6. 

Expected Unlock-burn-ht: Post prepare phase of cycle 6  #678650

**Actual result**
 What happened right now is the start-burn-ht is from 670,169 within prepare phase of cycle 2 and unlock-burn-ht is 676550(End of cycle 5 prepare phase)  that is incorrect. 

This makes me not eligible for cycle 5. So from a Stacker, who locks for 3 cycles, I am being eligible only for 2 cycles now. 

**Transaction Details for this scenario:**https://explorer.stacks.co/txid/0x9f7c10529f8d0b5019ca45eb8d713aa8e2ab2cde4cb7a5509c1747e8ac7498d5?chain=mainnet

**Note**:
  I noticed the calculations are correct if any Stackers lock STX, not during the prepare phase. Example transaction I referred https://explorer.stacks.co/txid/0x6fd4b544f16f504edab761b96d3a7ebc5d7b8eda73bc3889b6e6c6643bf34c8b?chain=mainnet

Here start-burn-ht is 674,452 
Cycle 4 start #674350
Lock period : 3 cycles
This Stacker is eligible for Cycles 5,6,7.

unlock-burn-ht: 682,850 (End of prepare phase of cycle 8) - This is correct.

**Comment by jcnelson** [comment]
A couple points of clarity.

First, the prepare phase for reward cycle _N + 1_ occurs at the _end of_ reward cycle _N_.  Cycle 2 begins at height 670250; the prepare phase from blocks 670150 through 670250 is still in Cycle 1 (websites like https://stacking.club don't precisely reflect the way the code actually works).

Second, your `stack-stx` needs to be mined on the canonical fork prior to height 670150 in order to get counted in Cycle 2.  This is because, per SIP-007, the PoX anchor block determines the reward set.  But, the anchor block will necessarily have been mined no later than 100 blocks prior to the start of the next reward cycle (but it can be arbitrarily earlier).  Any successful `stack-stx` call with a `start-burn-ht` of 670169 would be mined in Cycle 3, meaning it would potentially become part of the reward set for Cycle 4.  This is because the PoX anchor block selected at the end of Cycle 3 (the prepare phase for Cycle 4) is the earliest such PoX anchor block that can include your reward address.

This is reflected in `stack-stx`.  The first reward cycle you Stack in is the first whole reward cycle after the one in which your `stack-stx` is mined.  Per your first linked transaction, you Stacked for 3 reward cycles beginning at Cycle 4, so your tokens unlock at the _end of_ Cycle 7 / _beginning of_ Cycle 8 (height 678650).

Per your second linked transaction, the `stack-stx` had a `start-burn-ht` of 674452.  This means it was mined within Cycle 4, so it would be included in the reward set for the PoX anchor block mined for Cycle 5.  It locks for 3 reward cycles, so it would unlock at the _end of_ Cycle 8 / _beginning of_ Cycle 9 (height 682850).

Hope this clarifies things!

**Comment by HariniRajan397** [comment]
Thanks for the clarifications, Jude. I still need few more clarifications. Thanks in advance for that. 

I understand that Cycle 2 begins at 670250, I locked my STX at 670169, which is in Cycle 1. My stack-stx transaction was mined in cycle 3. Till this I am clear. 

As per your previous comment, I should be eligible for reward cycles 4, 5, 6. But looks like my address was added in the reward set of cycle 3 (started at block  #672350). I am confused with the cycle numbers. So leaving the numbers and talking based on blocks below. 

According to my understanding, cycle 3 is from  672350, cycle 4 from 674450-676550, and cycle 5 from 676650-678650.

Considering this is correct, now I expect my tokens to unlock at 672350+6300 (2100*3)i.e 678650. 
But my tokens are unlocking at #676550 (one cycle prior)- Which is still incorrect. 


Te current unlock block no is 676550 and it stops me from participating in one cycle, even though I lock the tokens for 3 cycles.

**Comment by jcnelson** [comment]
Let's reverse-engineer this.  I think my numbers are mixed up.

If you look at the PoX source code: https://explorer.stacks.co/txid/SP000000000000000000002Q6VF78.pox?chain=mainnet, you'll see that the `unlock-burn-ht` is calculated as `(reward-cycle-to-burn-height (+ first-reward-cycle lock-period))`.  Because this value is 676550, and because we know `lock-period` is 3, and the reward cycle length is 2100, then we have `676550 = 2100 * (first-reward-cycle + 3) + 666050)`.  Solving for `first-reward-cycle`, we get 2.

Since we know `first-reward-cycle` is 2, we can look at the beginning of the method and see this:

```
    ;; this stacker's first reward cycle is the _next_ reward cycle
    (let ((first-reward-cycle (+ u1 (current-pox-reward-cycle)))
          (specified-reward-cycle (+ u1 (burn-height-to-reward-cycle start-burn-ht))))
      ;; the start-burn-ht must result in the next reward cycle, do not allow stackers
      ;;  to "post-date" their `stack-stx` transaction
      (asserts! (is-eq first-reward-cycle specified-reward-cycle)
                (err ERR_INVALID_START_BURN_HEIGHT))
```

So, `(current-pox-reward-cycle)` must evaluate to 1, as well as `(burn-height-to-reward-cycle start-burn-ht)`.  So, we know that 670169 is in reward cycle 1 -- the same reward cycle in which this call to `stack-stx` was mined (otherwise, this `(asserts! ..)` would fail).

Your reward address is scheduled as follows (this is the data-map that the node reads out of when it calculates the reward set for a given reward cycle):

```
      ;; add stacker record
      (map-set stacking-state
        { stacker: tx-sender }
        { amount-ustx: amount-ustx,
          pox-addr: pox-addr,
          first-reward-cycle: first-reward-cycle,
          lock-period: lock-period })
```

So, your address was definitely scheduled in reward cycles 2, 3, and 4.  Your tokens would be unlocking at the end of reward cycle 4, which is 676550.

If you didn't see any payout in cycle 2, that doesn't mean that the address wasn't scheduled.  It may mean that no miner mined in the block(s) in which your address was up for payment.  This can happen by accident if, for example, two Bitcoin blocks arrive in rapid succession, before Stacks miners have a chance to react.

**Comment by HariniRajan397** [comment]
Got it, This is very clear @jcnelson. Thanks a lot for the clarification. 

After going through all this, I have two final questions.

1) I understand that the Prepare phase of cycle N is actually the last 100 blocks of cycle N-1(previous cycle).  If a "stack-stx" transaction is being initiated, during the prepare phase, then that particular address will be added to the reward set of cycle N.  Is it true always? Or are there possibilities that the address may also be sometimes added after N+1(Next cycle)? In my case, I initiated during prepare phase of the cycle  (during the last 100 blocks of cycle 1). Luckily mine got mined and added to cycle 2. Will it happen all the time? I am asking this question to know the best practice. 

 2) Also, how can I find the list of reward-address eligible for a current cycle? Stacking club doesn't seem like showing the correct info, I am seeing my address listed in 3,4,5 instead of 2,3,4 and it caused me confusion. Hence the question.

Thank you again for the help and support !!

**Comment by HariniRajan397** [comment]
Closing this as it's not a valid issue.
