### ISSUE TITLE
Extension contract: buff, string-ascii, and string-utf8 comparison

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2618]
There needs to be an extension contract that makes all sequence-types comparable (`<`, `<=`, `==`, `!=`, `>`, `>=`).  It could take arguments that have the type that represents the maximum allowed of the sequences, and has runtime equal to the longest of the two compared sequences.

**Comment by gregorycoppola** [comment]
I have a demo for this that doesn't use the argument for "maximum sequence length".

1) Do we need an argument for maximum sequence length? It seems to me like the interface is simpler if we omit this argument, and then calculate run-time cost based on the sequence lengths dynamically.

2) Should we gate this so that it only allows the additional types to be used if the ClarityVersion >= 2? (I guess so.)

3) What about generic lists (i.e., "(list A)")? I'm guessing that this would not be supported because, in general, element types are not comparable?

**Comment by jcnelson** [comment]
> I have a demo for this that doesn't use the argument for "maximum sequence length".

Yup, makes sense. We're adding this as a new native function now, instead of an extension contract, so there's no need to worry about a Clarity-representable type signature.

> Do we need an argument for maximum sequence length? It seems to me like the interface is simpler if we omit this argument, and then calculate run-time cost based on the sequence lengths dynamically.

No, not anymore.  If it's a native function, it doesn't need a Clarity-representable type signature.

> Should we gate this so that it only allows the additional types to be used if the ClarityVersion >= 2? (I guess so.)

Yes.

> What about generic lists (i.e., "(list A)")? I'm guessing that this would not be supported because, in general, element types are not comparable?

Correct.  For example, `(< true false)` is a nonsensical function application.
