### ISSUE TITLE
Use OP_RETURN for PoB

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2781]
**Is your feature request related to a problem? Please describe.**
During some block, the PoX requires to burn btc. Burning btc using a burn address is not bitcoin-friendly.

See https://forum.stacks.org/t/bitcoin-friendly-pox-burning/11858

**Describe the solution you'd like**
Use OP_RETURN burning during PoB blocks.

**Comment by 314159265359879** [comment]
Can you explain a bit more about the advantage this would have, how it works?

In one of the earlier iterations of the Stacks chain I recall that PoB was explained as a way to make Bitcoin sustainable in the very long term. I understood this:
Burning Bitcoin in PoB would actually lower the circulating supply of BTC, which means miners will be able to mine and claim coinbases for as long as PoB is active and mined BTC does not exceed Burned BTC amount... max supply/21,000,000 BTC is never reached. 

Does you solution pertain to this actually lowering the supply?

**Comment by friedger** [comment]
This is only about the way how to burn bitcoins. There are two ways to do it. I couldn't find the relevant code.

This issue is about clarifying which method is used and if not via OP_RETURN whether this should be changed.

**Comment by jcnelson** [comment]
The reason block-commits burn BTC by sending it to an unspendable address instead of an OP_RETURN is to ensure that the size of the block-commit transaction (and thus the BTC transaction fee) remains the same regardless of whether or not PoB or PoX is active.  This is necessary to ensure that miners don't get incentivized to disable PoX.  If miners burnt BTC by sending it to an OP_RETURN output, then a PoB block-commit would be *cheaper* than a PoX block-commit, and if BTC transaction fees get high enough, this could encourage miners to deliberately prevent PoX from activating in a prepare phase in order to reduce their BTC spend (and increase their profits).

**Comment by friedger** [comment]
Thank you for the clarification!
