### ISSUE TITLE
Fee estimation: Update block assembly to use estimator and fee rate ordering

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2834]
Per #2825, miner block assembly needs to be updated such that iteration is ordered by estimated fee rate. This work would also include _updating_ the estimator with the output of tentatively executing transactions: that is, if a particular contract-call has never been seen before, it should be tentatively executed to obtain a cost estimate, and rolled back if the fee rate turned out to be too low.

**Comment by kantai** [comment]
In order to make the mempool iteration a little easier to reason about, in implementing this, I am proposing to restructure the mempool iterator to do the following:

1. Add a new method `MempoolDB::prepare(&self, &mut ClarityConnection)` that will:
    1. Read the current account nonce for every origin (and sponsor) in the mempool
    2. Estimate the ExecutionCost for each transaction in the mempool
    3. Write this data to a side table in the mempool db (which will get wiped before the write)
2. `MempoolDB::iterate_candidates` will, instead of the current `find_origin_addresses_by_descending_fees` call, perform a SQLite query like:
    1. `SELECT tx FROM mempool as m INNER JOIN sidetable as s ON m.txid = s.txid WHERE m.origin_nonce = s.origin_nonce + 1 AND m.sponsor_nonce = s.sponsor_nonce + 1 AND s.scalar_cost IS NOT NULL ORDER BY CAST(m.tx_fee as REAL) / CAST(s.scalar_cost as REAL) DESC LIMIT 1`
    2. After applying a transaction, update the nonces stored in the side table.
    3. With some probability, instead of the above query to get the next TX, explore a `s.scalar_cost IS NULL` transaction, or if there are only such transactions.

The advantage of this approach is that it makes it _much_ more clear how the mempool is being ordered/considered. The disadvantage is that it front-loads a lot of MARF reads (the account nonce reads) -- would be happy to consider alternatives, but the current approach has a _lot_ of downsides: iterating by selecting the origin adress can have many unintended consequences for sorting, for example, clumping origin transactions together, or rewarding origin addresses that have one high-fee transaction (possibly already confirmed) by confirming their other low-fee transactions before other accounts.

**Comment by jcnelson** [comment]
Some feedback

In 1(i), how do you deal with intermittent chain reorgs?  You'll need to invalidate the cached nonces.  Does this happen at every block -- i.e. we re-calculate this state each time the chain tip changes?  Also, when does this happen in the epoch lifeycle?  Is it done lazily, on first block mine?  Or is it done once the new block arrives?

In 2(i), when would `s.scalar_cost` be `NULL`?  Does the estimator not run on each candidate transaction?

> The disadvantage is that it front-loads a lot of MARF reads (the account nonce reads

One way to bound the number of MARF reads would be to only query accounts that have changed when the last block was applied.  You could even update the `StacksTransactionReceipt` structure to include the nonce for each origin and sponsor account, if it's not reporting this already.  Then, in the happy path where a block gets built on top of the best chain tip, you wouldn't need *any* MARF reads -- you'd just update the side table with the new nonces using the receipts.  The unhappy path would, however, require some MARF scanning (but this could be mitigated by keeping multiple recent side tables resident -- e.g. all the side tables for blocks that are within 6 blocks of the current chain tip -- and falling back to the right side table in the event of a short fork).

> the current approach has a lot of downsides: iterating by selecting the origin adress can have many unintended consequences for sorting, for example, clumping origin transactions together, or rewarding origin addresses that have one high-fee transaction (possibly already confirmed) by confirming their other low-fee transactions before other accounts.

The current approach does the opposite of clumping, actually.  Origin addresses are considered in a round-robin fashion.  If I have 10 transactions pending that are mineable, then once my first transaction is selected, my second one won't be considered until all other origin addresses are considered.  This is because in the current approach, the miner has to call `::iterate_candidates` multiple times until the block is full.  But I agree with the other points -- the current code is meant to be a stop-gap that leaves a lot to be desired.  I'm looking forward to getting it replaced with your code.

**Comment by kantai** [comment]
> In 1(i), how do you deal with intermittent chain reorgs? You'll need to invalidate the cached nonces. Does this happen at every block -- i.e. we re-calculate this state each time the chain tip changes? Also, when does this happen in the epoch lifeycle? Is it done lazily, on first block mine? Or is it done once the new block arrives?

This is run everytime `build_anchored_block` is called -- so, yes, it'd run at every block. This could probably be avoided for the cost estimate -- those could be fairly safely kept around between blocks -- but it is necessary for the account nonces. This isn't as expensive as it sounds -- we already need to do account nonce lookups for every transaction considered in the mempool (up to the block limit/timeout).

> In 2(i), when would s.scalar_cost be NULL? Does the estimator not run on each candidate transaction?

If the estimator hasn't received any information for a contract-call before, it wouldn't be able to create an estimate for the runtime of the transaction.

> One way to bound the number of MARF reads would be to only query accounts that have changed when the last block was applied. You could even update the StacksTransactionReceipt structure to include the nonce for each origin and sponsor account, if it's not reporting this already. Then, in the happy path where a block gets built on top of the best chain tip, you wouldn't need any MARF reads...

Something like this could work, but I'm a little wary of depending on this state being kept in sync with the chainstate -- it'd involve a fair amount of complexity, and could lead to some pretty hard to diagnose issues.

Something else I was thinking about was structuring the nonce lookup lazily (sort of like is done now), by emptying the side table at the start of assembling a new block, but instead of filling it proactively, just going ahead and selecting the highest fee rate transaction where the account nonce is correct _or_ the side table doesn't have the current nonce, updating the side table with the account nonce for that transaction (if it wasn't filled), and then requerying: i.e.,

1. Fill side table with cost estimates.
2. Query: `SELECT tx FROM mempool as m INNER JOIN sidetable as s ON m.txid = s.txid WHERE ((m.origin_nonce = s.origin_nonce + 1 AND m.sponsor_nonce = s.sponsor_nonce + 1) OR (s.origin_nonce is NULL)) AND s.scalar_cost IS NOT NULL ORDER BY CAST(m.tx_fee as REAL) / CAST(s.scalar_cost as REAL) DESC LIMIT 1`
    1. If `s.origin_nonce` was null, query the account nonce, and fill in the side table with the nonce, return to 2.
    2. If `s.origin_nonce` was not null, then try to include this transaction, update the side table with any subsequent nonce updates and then return to 2.

That way, the mempool iteration would still be iterating by transaction fee rate (and whatever additional statements get added to that `ORDER BY` clause), but we would only look up the account nonces as the block got filled.
