### ISSUE TITLE
Blocks mined with less then 10 transactions when the mempool has plenty

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/stacks-blockchain#2918]
**Describe the bug**
![image](https://user-images.githubusercontent.com/33360391/141181021-c398141a-a5f6-46ec-8d2e-5a8c9fb05fa0.png)

**Steps To Reproduce**
See these recent blocks:
https://explorer.stacks.co/block/0xdf69a583b84d0b39eb736ad50531fb49a01d648d5e9af0282e41acc485f7cab5?chain=mainnet
https://explorer.stacks.co/block/0x0ca5b59ccf351ca239c08867d6c8a670e0190e5756fd2ee25e0d206d171e8a0e?chain=mainnet

**Expected behavior**
I expect a lot more transactions in a block when there is so many available in the mempool. These blocks don't look like they have any particularly "expensive" transactions either.

**Comment by Eshwari007** [comment]
cc @pavitthrap @lgalabru

**Comment by jcnelson** [comment]
Blocks are filled based on how much compute resources a transaction uses, and miners prioritize transactions by revenue.  A miner will build a block with a few expensive transactions that pay higher fees before it will build a block with many cheap transactions that pay lower fees.

**Comment by diwakergupta** [comment]
> I expect a lot more transactions in a block when there is so many available in the mempool. These blocks don't look like they have any particularly "expensive" transactions either.

There are a lot of factors that can influence how many transactions get included in each block:

- time between blocks: there was < 2 min gap between Bitcoin blocks 709109 and 709110 (latter is the Bitcoin height at which STX block 37316 was mined)
- other transactions in the mempool: if you run a miner or run a node in the "mock mining" mode, you can observe the default miner behavior. Around the time of this block, I see in our logs a lot of transactions being skipped due to `BlockLimitFunction::LIMIT_REACHED`
- different miners are free to make different choices in exactly which transactions they choose to package in a given block. Presumably most miners are using the default miner implementation, but it's impossible to be sure.

The new release just went out today improves the default miner behavior. Quoting @jcnelson from Discord: "Specifically, over the last 24 hours, it has produced blocks with 59% more fees than 2.0.11.3.0." -- so I would hope anyone running a miner upgrades!

Improvements to block limits are already in-flight via SIP-012.

Absent something concrete that's not already captured elsewhere, I'm not sure there's anything else that's actionable here.

**Comment by 314159265359879** [comment]
Thank you for the responses, makes sense that this happens with the BTC blocks arriving in such rapid succession. I will close this item it does not look like a bug upon further inspection.
