### ISSUE TITLE
Search: Replace /v1/users endpoint with a node.js microservice

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/stacks-blockchain#577]
@kantai we're upgrading our verifications system to use addresses instead of names (https://github.com/blockstack/blockstack.js/issues/250) and adding support for additional services (https://github.com/blockstack/blockstack.js/issues/251).

To avoid having to maintain both a python and a javascript version of the proofs library, can we use blockstack.js to replace blockstack-proofs-py in the resolver and search code?

**Comment by kantai** [comment]
Yes -- this should definitely be doable, there are a couple different python libraries that can use various javascript engines to load JS code.

**Comment by kantai** [comment]
This is currently living in `develop-resolver-blockstackjs` -- it shells out to nodejs, which means that we'll want to make doubly sure that the inputs are sanitized.

**Comment by jackzampolin** [comment]
This would be cool!

**Comment by jcnelson** [comment]
@kantai has this shipped?

**Comment by kantai** [comment]
In the case we wanted to do that, I'd say we rename this issue to "replace `/v1/users` endpoint with a node micro-service"

This makes more sense anyways, because we basically have two full re-implementations of the profile parsing, verification, code as it stands today -- one in blockstack-core's python libraries, and one (the reference implementation) in `blockstack.js`

**Comment by jcnelson** [comment]
Sounds good -- renamed.
