### ISSUE TITLE
Automate testing the API documentation against the API

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#801]
Add an integration test to scan the documentation template, extract the requests and response schemas, and verify that each request matches the given response schema.

**Comment by vsund** [comment]
Just to throw in some tooling (I played recently around with auto generating a TypeScript client for these endpoints).
* https://github.com/apiaryio/drafter-npm
* https://github.com/kylef/draughtsman

Also I then decided to do it [manually](https://github.com/ntzwrk/blockstack-core-client.ts) (for now), because the specification wasn't in a consistent and complete format :/

And also I'd like to throw in switching over to [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification#readme), because I experienced a way better tooling there :) Worked multiple times with it (and their spec) and it was a great experience (have to add though that I didn't work this extensively with API Blueprint).

**Comment by moxiegirl** [comment]
@jcnelson I'd actually like to test each shipped sample with a build. It should be easy to get each code sample and run it to make sure it at least builds/runs.
