### ISSUE TITLE
Support configuration of the time a consensus hash is valid per namespace

### ISSUE THREAD

**Issue by bodymindarts** [blockstack/stacks-blockchain#833]
In order to create a blockstack id that is backed by a multi sig address, custodians of the address must coordinate and sign the PREORDER and REGISTER transactions within the time frame that the consensus hash that is used to generate the transactions is valid. Depending on the number of custodians this can be difficult to coordinate. Allowing a namespace to set a longer time would make it easier for the coordination to occur in the required time frame.

**Comment by jcnelson** [comment]
Just providing some background on what this will entail:

# Background

The consensus hash is a mechanism that partitions set of (non-enumerable) Blockstack nodes into fork-sets.  Each Blockstack node assigns each block a consensus hash that is cryptographically derived from the sequence of name operations it has processed.  If two Blockstack nodes have the same view of the blockchain, and follow the same rules, they will each derive the same sequence of consensus hashes (w.h.p).  Conversely, if two Blockstack nodes do NOT have the same view of the blockchain, or do NOT follow the same rules, they will derive a DIFFERENT sequence of consensus hashes (w.h.p) from the block at which they disagree, and forever after (w.h.p).  This is what makes Blockstack nodes fork*-consistent.

When a Blockstack client announces a name operation, it selects which fork-set the name operation will be destined for by including a *recent* consensus hash in the name operation.  This way, only nodes in the same fork-set as the client will consume the name operation.  Nodes in other fork-sets will ignore it.

# Problem Statement

Names can be owned by multi-sig addresses, and the keys represented by those addresses can be held by different parties.  In order to send a name operation, the parties must each sign a name operation derived from a *recent* consensus hash.  This significantly limits the amount of time the parties have in order to generate the name operation.  The current implementation mandates that consensus hashes are valid for 24 blocks, or about 4 hours.  For systems like Misthos, this means that owners of a named venture would need to be online within the same 4 hour window in order to issue a name operation.  This leads to a bad user experience.

# Proposed Solution

Instead of mandating that a consensus hash is valid for 24 blocks globally, we make the number of blocks configurable on a per-namespace basis.  A namespace could allow a name operation to use a consensus hash older (or younger) than 24 blocks and still be valid.

The biggest consequence of this solution is that in the event of there being multiple emerging fork-sets, a name operation could be valid in all of them for a much longer period of time than 24 blocks.  In other words, operations in one fork-set could be replayed in other fork-sets.  This applies to operations generated *before* the conflicting fork-sets emerged, but got delayed in the mempool so that they are processed in both fork-sets after the fork occurs.  Clients that are aware of the emerging fork-sets would avoid this by selecting a newer consensus hash that occurs *later* in the desired fork-set's history than the fork itself, so other fork-sets will (rightfully) ignore the name operation.

The consensus hash validity window would only affect name operations and (should it be implemented) namespace-specific tokens. It would *not* affect the consensus hash check for the Stacks token.

# Alternatives

## Subdomains

The motivation for this solution is that names can be owned by multiple people who need to coordinate updates in a timely fashion.  This could also be addressed by using a subdomain name instead of an on-chain name.

Unlike on-chain names, subdomains do not require consensus hashes to update.  An update can be signed off on by each key holder over an arbitrarily long timescale.  Moreover, updating and transferring subdomains is considerably cheaper if done in batches with other subdomains.

If a trusted subdomain registrar is available for broadcasting the signed updates and transfers, then this problem can be addressed today.

## Shared Records in Gaia

In the context of application-specific assets owned by multiple parties, an alternative to using the on-chain naming system for binding assets to users is to implement named shared records at the application level.  A shared record would only be considered valid by the application if it was signed by a requisite set of keys (also determined by the application).

For example, `alice.id` could create a shared venture file in her Gaia bucket for Misthos that `bob.id` and `carol.id` can read, and must sign in order for the Misthos client to consider valid.  To do this, the Misthos client would allow both `bob.id` and `carol.id` to read the venture, and sign and store their respective signatures over the shared venture in their respective Gaia buckets.  Later, `alice.id` would copy and retain a record of their signatures.  If desired, any of the participants can notarize the signatures via a notary.

**Comment by bodymindarts** [comment]
Thank you so much for this detailed description @jcnelson.
Just a comment regarding the `Shared Records` alternative. Unfortunately this doesn't fulfil some important requirements of what we want to achieve via the venture id.

The Id should be publicly discoverable and be a way for 3rd parties to access data that has been determined by the constituent partners of the venture to be publicly accessible.
It should be possible for the 3rd parties to verify the integrity of the data, via verifying the signatures against public keys associated with the id but also allow the partners to keep their individual blockstack ids private if they want.

**Comment by jcnelson** [comment]
I updated the comment to explain how the shared records alternative could be realized with an indexer.
