### ISSUE TITLE
`/v1/addresses/bitcoin/:address` does not resolve for pending subdomains.

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#897]
I'm working on the custom Gaia hub PR in the Browser, and I'm currently storing API configuration in their `profile.json`. I now need to support using this API info when restoring a profile, so that the Gaia URL is set correctly.

An issue is that, when restoring an account, the Browser requests `v1/addresses/bitcoin/:address` to try and get the zonefile. If this is a subdomain, this API doesn't return anything until the subdomain is registered.

Is it possible to have this API work for pending subdomains, or will I have to go with some other route?

If the subdomain is not at all accessible before it's confirmed, we'd have to update the onboarding flow to ask for a Gaia URL, and we're trying to not complicate the UI here.

**Comment by jcnelson** [comment]
This is not feasible, since the Core node has no way of knowing which subdomain registrar to query if it only knows the subdomain owner's address.  The subdomain owner address may not even be on the blockchain, so there's no way to automatically discover this information.

If you need this functionality, then you'll need some way of determining out-of-band which subdomain registrar to query.  It is possible to add this API route to the subdomain registrar so it can do address-to-name lookups on pending subdomains.

**Comment by jcnelson** [comment]
Yeah, that would work.  You could also save only the subdomain registrar in the profile if you want to preserve a degree of anonymity (i.e. you'd need both the profile and secret seed to discover the name).

**Comment by hstove** [comment]
But how do you even know where the `profile.json` is before it's ever on the blockchain? That's the issue here.

**Comment by kantai** [comment]
> But how do you even know where the profile.json is before it's ever on the blockchain? That's the issue here.

The user's browser knows where it would live once the user restores from keychain.

**Comment by markmhx** [comment]
@hstove these seems like an edge case as far as the expected user experience, yea?

In that, only users who are trying to register names with subdomains within the window in which it's still pending would encounter this?
