### ISSUE TITLE
BNS smart contract wishlist

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#988]
When we port BNS to a full-fledged smart contract, I propose adding the following:

- [ ] Support for arbitrary byte strings as names and namespaces, instead of the base-40 alphabet we use now
- [ ] Arbitrarily long names -- i.e. as long as the `buff` type will allow.

**Comment by larrysalibra** [comment]
" Support for arbitrary byte strings as names and namespaces, instead of the base-40 alphabet we use now" sounds dangerous - the current lowercase character set we restrict names to significantly reduces the potential for phishing with names that look the same to the human eye but are actually different. 

example -> larry vs Iarry
